### ISSUE TITLE
Kubeflow listed as available AArch64 addon, but missing enable script

### ISSUE THREAD

**Issue by benjcunningham** [ubuntu/microk8s#1091]
Per #1086, and my (limited) understanding from Kubeflow discussion elsewhere, I gathered that KF probably wouldn't be available on AArch64 MicroK8s. I was surprised then when `microk8s enable --help` showed Kubeflow on the list, and also when I double-checked the supported architectures in [`addon-lists.yaml`](https://github.com/ubuntu/microk8s/blob/5d09320265868b32504bf20b1ee05c8cdb341097/microk8s-resources/wrappers/addon-lists.yaml#L138).

However, when I tried running `microk8s.enable kubeflow`, I got `Nothing to do for kubeflow`, which I believe I've traced back to the fact that `${SNAP}/actions/enable.kubeflow.sh` doesn't exist.

Is this expected behavior? I mostly just wanted to report this since I found it odd that KF is ostensibly listed as an available add-on, but the script to enable doesn't seem to be shipped with the snap I installed. I suspect I may just be misunderstanding something here too.

I believe I'm using a fresh installation of the latest stable version as of today, but here's the inspect archive for good measure. Thanks!

[inspection-report-20200403_210033.tar.gz](https://github.com/ubuntu/microk8s/files/4430542/inspection-report-20200403_210033.tar.gz)

**Comment by ktsakalozos** [comment]
Thank you for spotting that @benjcunningham. You are right we should not be showing the kubflow addon on arm64 arch. The respective PR addresses this.

**Comment by matthiaslau** [comment]
Is there more information on why the gpu and kubeflow addons are not available for ARM64? Is this something on the roadmap?

**Comment by ktsakalozos** [comment]
To the best of my knowledge currently there are no immediate plans to support gpus on ARM64 in MicroK8s. For Kubeflow I know there is work towards supporting ARM64 from upstream but I hear some parts of the ecosystem are missing. There have to be some incentives for Canonical to take up this task.

Out of curiosity, what specific hardware are you interested in? I am interested in the CPU specs and the paired GPUs. Thank you.

**Comment by matthiaslau** [comment]
Thank you for the answer! :-) I am currently working with a cluster of NVIDIA Jetson Nanos (GPU: Maxwell with 128 Cores, CPU: Quad-Core-ARM A57 with 1,43 GHz). It is also interesting to expand the cluster with Jetson Xavier (GPU: Volta with 512 Cores, CPU: 8 ARM-v8.2-64-Bit-CPU-Cores).

It would be really great if GPU and Kubeflow will be supported in the future as microk8s would be a good fit for this hardware. But I see the difficult dependencies especially for kubeflow.

**Comment by MrXinWang** [comment]
Hi @matthiaslau , I saw this issue in the kubeflow community under my reply, also as I am working on enabling kubeflow on arm64, I think I can answer some of your questions:

1. I did tried NVIDIA Jetson board with kubeflow several months ago, but I used Jeston TX2 board. With that board you can passthrough the GPU to k8s cluster by adding volumes for GPU drivers, like below, and this worked well on my device, but due to the limitation of memory on that board, basically any tensorflow training job will run out of the memory. As we also need to disable swap when building k8s cluster, we cannot adding memory to it...

```yaml
volumeMounts:
            - mountPath: /pets_data
              name: pets-data
            - mountPath: /usr/lib/aarch64-linux-gnu
              name: aarch64-linux-gnu
            - mountPath: /usr/local/cuda/lib64
              name: cuda-lib64
            - mountPath: /usr/lib/aarch64-linux-gnu/tegra
              name: aarch64-linux-gnu-tegra
            - mountPath: /dev/nvhost-ctrl
              name: dev-nvhost-ctrl
            - mountPath: /dev/nvhost-ctrl-gpu
              name: dev-nvhost-ctrl-gpu
            - mountPath: /dev/nvhost-prof-gpu
              name: dev-nvhost-prof-gpu
            - mountPath: /dev/nvmap
              name: dev-nvmap
            - mountPath: /dev/nvhost-gpu
              name: dev-nvhost-gpu
            - mountPath: /dev/nvhost-as-gpu
              name: dev-nvhost-as-gpu
            workingDir: /models

volumes:
          - name: pets-data
            persistentVolumeClaim:
              claimName: pets-pvc
          - hostPath:
              path: /usr/lib/aarch64-linux-gnu
              type: Directory
            name: aarch64-linux-gnu
          - hostPath:
              path: /usr/local/cuda/lib64
              type: Directory
            name: cuda-lib64
          - hostPath:
              path: /usr/lib/aarch64-linux-gnu/tegra
              type: Directory
            name: aarch64-linux-gnu-tegra
          - hostPath:
              path: /dev/nvhost-ctrl
              type: File
            name: dev-nvhost-ctrl
          - hostPath:
              path: /dev/nvhost-ctrl-gpu
              type: File
            name: dev-nvhost-ctrl-gpu
          - hostPath:
              path: /dev/nvhost-prof-gpu
              type: File
            name: dev-nvhost-prof-gpu
          - hostPath:
              path: /dev/nvmap
              type: File
            name: dev-nvmap
          - hostPath:
              path: /dev/nvhost-gpu
              type: File
            name: dev-nvhost-gpu
          - hostPath:
              path: /dev/nvhost-as-gpu
              type: File
            name: dev-nvhost-as-gpu
```

2. Several months ago I built and run kubeflow 0.5.1 on microk8s for arm64. Currently I am working on supporting kubeflow master branch on arm64, I have contributed most of patches to kubeflow community.
