### ISSUE TITLE
Problem accessing Kubeflow GUI through svc/istio-ingressgateway

### ISSUE THREAD

**Issue by Byest** [ubuntu/microk8s#1128]
Hey all :) Hope all is well~~

We installed microk8s 1.18 on ubuntu and enabled kubeflow, istio, knative, dns, dashboard, registry, and maybe a couple of others.
We can access the Kubeflow GUI through svc/ambassador,
but the svc/istio-ingressgateway clusterip and external-ip seem to not work at all.
All the istio-system pods and resources seem to be ready and completed.
Is there some manual configuration that is needed in order to connect istio-ingressgateway with the Kubeflow GUI?

This is partially because we are trying to port-forward the external-ip so our local network computers that are not in the k8s cluster can access the GUI (though not sure if this even possible with dex);
and partially because we are going to try to get KFServing up and running, which requires Istio, and I'm worried the Istio IPs not working might also cause problems with KFServing.

Any help would be greatly appreciated. Been stuck on this for days (I'm thinking I'm gonna feel silly at how basic the solution is). Also, thanks for the work you all have done so far. It's a very beautiful and elegant product :)

[inspection-report-20200419_171338.tar.gz](https://github.com/ubuntu/microk8s/files/4500315/inspection-report-20200419_171338.tar.gz)

**Comment by knkski** [comment]
It sounds like Ambassador and svc/istio-ingressgateway both work fine for you. Are you able to add a VirtualService like this to include Ambassador into Istio?

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ambassador
spec:
  hosts:
    - localhost
  http:
  - route:
    - destination:
        host: ambassador
```
