### ISSUE TITLE
Configuring Ingress Controller for TCP and UDP

### ISSUE THREAD

**Issue by trulede** [ubuntu/microk8s#1149]
I've configured the Ingress Controller to proxy TCP (and UDP) ports in much the same way it works with HTTP/HTTPS. This involved patching the DaemonSet and adding a few ConfigMaps.

```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-microk8s-conf
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp-services-conf
        - --udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp-services-conf
        - --publish-status-address=127.0.0.1
        name: nginx-ingress-microk8s
```

and

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-services-conf
  namespace: ingress
data:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-udp-services-conf
  namespace: ingress
data:
```

It's been tested with Redis (these files need to be patched again for port 6379) and it seemed to work. Would you be interested in a PR to add this to the default Ingress Controller configuraiton/deployment?
