### ISSUE TITLE
Prometheus add-on pods cannot not start on arm64 nodes

### ISSUE THREAD

**Issue by ssmall** [ubuntu/microk8s#1204]
It appears that the deployments created by the Prometheus operator are not using multi-arch images. After running `microk8s enable prometheus` I see the following:

```bash
$ kubectl get -n monitoring po                                                                                                                                                   [3:15:18]
NAME                                  READY   STATUS             RESTARTS   AGE
grafana-5fd6b9c649-75b4w              1/1     Running            0          11m
kube-state-metrics-dcc94d9f8-bkh5t    0/3     CrashLoopBackOff   15         5m56s
node-exporter-dz865                   2/2     Running            0          25m
node-exporter-f27mk                   1/2     CrashLoopBackOff   9          25m
node-exporter-grrkf                   2/2     Running            0          25m
node-exporter-hws6x                   2/2     Running            0          25m
node-exporter-s2x88                   1/2     CrashLoopBackOff   9          25m
prometheus-adapter-5949969998-8s5jj   1/1     Running            0          25m
prometheus-operator-5c7dcf954-jz6ls   0/1     CrashLoopBackOff   9          25m
```

When I inspect one of the crashing pods I see
```bash
$ kubectl logs -n monitoring pod/kube-state-metrics-dcc94d9f8-bkh5t -c kube-state-metrics                                                                                        
standard_init_linux.go:207: exec user process caused "exec format error"
```

I am able to fix the crashlooping pods by doing 
```bash
$ kubectl edit -n monitoring deploy/kube-state-metrics
```

and adding the following to `spec.template.spec`:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
```
