### ISSUE TITLE
Port Forwarding not working on fresh install

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1244]
Hi,

I've installed microk8s using `sudo snap install microk8s --classic --channel=1.18/stable` and installed the following addons `microk8s enable rbac dns storage` when I try to port-forward from another machine on the same internal network I'm getting this error.

```
error: error upgrading connection: unable to upgrade connection: Forbidden (user=127.0.0.1, verb=create, resource=nodes, subresource=proxy)
```

I've found this issue. https://github.com/charmed-kubernetes/bundle/issues/696

Could it be related?

**Comment by sstubbs** [comment]
I've tested on the same computer running microk8s using `microk8s kubectl port-forward and am getting the same error`

**Comment by balchua** [comment]
@sstubbs 
Can u try adding this? Just testing out.

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microk8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: front-proxy-client  
```

**Comment by sstubbs** [comment]
Thanks. I'm getting this error:
```
error: no objects passed to create
```
while trying to create this. You got me on the right track though I think. I'm having a look at this now and will try it too. https://medium.com/@ManagedKube/kubernetes-rbac-port-forward-4c7eb3951e28

**Comment by sstubbs** [comment]
I've tried this
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-port-forward
  namespace: default
subjects:
- kind: User
  name: admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: allow-port-forward
  apiGroup: ""
```
The objects do get created but it still doesn't forward as it seems to be connecting as user 127.0.0.1 rather than admin for some reason.

**Comment by balchua** [comment]
I've seen this before. I end up creating this ClusterRoleBinding.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microk8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: 127.0.0.1
```
I still dont know where the user `127.0.0.1` is coming from.

**Comment by sstubbs** [comment]
This doesn't work for me either. I wonder do I need to add a service account for 127.0.0.1?

**Comment by sstubbs** [comment]
I also was not able to access logs. I've applied this and can now access logs and port forward for now.
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "pods", "pods/portforward", "pods/log"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-port-forward
  namespace: default
subjects:
- kind: User
  name: 127.0.0.1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: allow-port-forward
  apiGroup: ""
```
However I do think there is possibly a bug with this version of the snap using user 127.0.0.1
