### ISSUE TITLE
express.js use fluent-logger reports ECONNREFUSED 127.0.0.1:24224

### ISSUE THREAD

**Issue by wtao-volvo** [ubuntu/microk8s#1316]
microk8s inspect tarbar [inspection-report-20200616_060335.tar.gz](https://github.com/ubuntu/microk8s/files/4784704/inspection-report-20200616_060335.tar.gz)

Ubuntu 20.04, microk8s 1.18/stable, addon enabled fluentd dns

Hi, In my express.js app, I followed the singleton example from the fluentd-logger, [https://github.com/fluent/fluent-logger-node](url)
```
var logger = require('fluent-logger')
logger.configure('tag_prefix', {
   host: 'localhost',
   port: 24224,
   timeout: 3.0,
   reconnectInterval: 600000 // 10 minutes
});
logger.emit('label', {record: 'this is a log'});
```

I provisioned fluentd's configMap, `kubectl edit configmaps/fluentd-es-config-v0.1.5 -n kube-system` to make sure the fluentd pods listens at 24224 port
<img width="338" alt="Screen Shot 2020-06-15 at 11 14 33 PM" src="https://user-images.githubusercontent.com/61992869/84738063-10b05680-af5e-11ea-9093-38893c8b6838.png">

But in my express.js app's log, it produced the following error, 
<img width="962" alt="Screen Shot 2020-06-15 at 11 21 10 PM" src="https://user-images.githubusercontent.com/61992869/84738545-f32fbc80-af5e-11ea-9b25-7c84779879fa.png">

Can anyone help on the issue? Is my way to modify the configMaps the correct way to enable listening?

**Comment by balchua** [comment]
The thing is `localhost` isn't pointing to the fluentd pod.

You probably need to
* expose the port `24244` in the fluentd daemonset.
Example:
```yaml
       ports:
        - name: http-port
          containerPort: 24224
          protocol: TCP
```
* Create a `Service` that can be linked to the `fluentd-ds`.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  namespace: kube-system
spec:
  selector:
    k8s-app: fluentd-es
  ports:
    - protocol: TCP
      port: 80
      targetPort: 24224
```
* From your code, instead of using `localhost`, use `fluentd-service.kube-system`.

Example:
```javascript
var logger = require('fluent-logger')
logger.configure('tag_prefix', {
   host: 'fluentd-service.kube-system',
   port: 80,
   timeout: 3.0,
   reconnectInterval: 600000 // 10 minutes
});
```
This is assuming your expressjs app is running as a pod.
