### ISSUE TITLE
preStop hooks are failing

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#138]
Here is how to reproduce:

Use this yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.11
        imagePullPolicy: Always
        name: nginx
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "/usr/sbin/nginx -s quit ; sleep 29"]
      restartPolicy: Always
```

`microk8s.kubectl create -f <the above yaml>`

`microk8s.kubectl delete <the pod created>`

`microk8s.kubectl get events`

You should see something like:
```
12m         Warning   FailedPreStopHook         Pod    Exec lifecycle hook ([bash -c /usr/sbin/nginx -s quit ; sleep 29]) for Container "nginx" in Pod "nginx-678cbdbf9b-9m994_default(78dd52bd-d2b0-11e8-9d2e-f8cab834928e)" failed - error: command 'bash -c /usr/sbin/nginx -s quit ; sleep 29' exited with 137: 2018/10/18 08:36:03 [notice] 13#13: signal process started
, message: "2018/10/18 08:36:03 [notice] 13#13: signal process started\n"
```
