### ISSUE TITLE
Kube config file token lost after "microk8s refresh-certs -i" in version 1503

### ISSUE THREAD

**Issue by Just4test** [ubuntu/microk8s#1391]
After I run `microk8s refresh-certs -i`, my microk8s can't work. I found it lost token in kubeconfig, and can't fix by `microk8s reset`.

```
$ microk8s kubectl get all
error: You must be logged in to the server (Unauthorized)
```
```
$ microk8s inspect
[sudo] password for ett:
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

WARNING:  Docker is installed.
Add the following lines to /etc/docker/daemon.json:
{
    "insecure-registries" : ["localhost:32000"]
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/1503/inspection-report-20200708_155654.tar.gz
```
```
$ microk8s config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J  # More, more, more
    server: https://192.168.11.252:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password:
```
```
$ cat /var/snap/microk8s/current/credentials/known_tokens.csv
b2RheTRTUFIyS1lpYldITzVkQ0QvczF3SER2NHEwYldqZFJXYnZsUVV6OD0K,admin,admin,"system:masters"
ZkJmZndYc1FDQ3RwUW5kWlpCU3oxOXVHVmpyNmNwVlVENHBsRnZMNEgrYz0K,system:kube-proxy,kube-proxy
a2RWVHY1UHNsTWEvMmtwRVV0SExEOG50ZlhJRm84RjZmY2lFS0xmalovUT0K,system:node:c7-wx-test-11-252,kubelet-0,"system:nodes"
T01PUzdsZjM4RE5ub1F4QTA4dXJ5MGMyQnVFNmlDZmxwMzBENEFvQXVqOD0K,system:kube-controller-manager,controller
aVpIckFtbk5BT0YvU0Q0U081N3FGQWhXb2JyUzc4djVveEV0WWhhVFJ1Yz0K,system:kube-scheduler,scheduler
```
So I create a kube config file manually. I delete "username: admin" and "password:", then add admin token:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J  # More, more, more
    server: https://192.168.11.252:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: b2RheTRTUFIyS1lpYldITzVkQ0QvczF3SER2NHEwYldqZFJXYnZsUVV6OD0K
```

With this kube config file, I can connect to the microk8s cluster and find it work normally.

[inspection-report-20200708_155654.tar.gz](https://github.com/ubuntu/microk8s/files/4889337/inspection-report-20200708_155654.tar.gz)
