### ISSUE TITLE
Ingress not working on AWS.

### ISSUE THREAD

**Issue by yasiemir** [ubuntu/microk8s#142]
I have a single node setup on AWS ubuntu instance using microk8s with ingress controller enabled by using
`microk8s.enable ingress`. 
Which has added the following service:
```bash
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
default-http-backend   ClusterIP   10.152.183.50   <none>        80/TCP    8m47s
```
and the following deployment: 
```bash
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default-http-backend   1         1         1            1           10m
```
which I belive is the ingress controller.

Now when I try to create the following ingress:
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: nodeserver
    servicePort: 7070
```
The `ADDRESS` is not assigned to the ingress
```bash
kubectl get ingress
NAME            HOSTS   ADDRESS   PORTS   AGE
basic-ingress   *                 80      12m
```
Is there anything specific to AWS loadbalancers that needs to be configured? Or anything that I am missing in the configuration?

I tried installing nginx ingress controller saperately but same issue with that.

**Comment by ktsakalozos** [comment]
Hi @yasiemir,

I am not sure what you want to achive with the ingress rule you provided. Here is how we expect ingress to be used in the microk8s.

As soon as you do a `microk8s.enable ingress` the ingres controller and the default backend should start.

```
> microk8s.kubectl get all --all-namespaces                                                                                               jackal-VGN-FZ11M: Mon Oct 22 18:16:02 2018

NAMESPACE   NAME                                          READY   STATUS    RESTARTS   AGE
default     pod/default-http-backend-587b7d64b5-2jjp9     1/1     Running   0          2m31s
default     pod/nginx-ingress-microk8s-controller-w5rml   1/1     Running   0          2m31s

NAMESPACE   NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
default     service/default-http-backend   ClusterIP   10.152.183.197   <none>        80/TCP    2m31s
default     service/kubernetes             ClusterIP   10.152.183.1     <none>        443/TCP   89m

NAMESPACE   NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
default     daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>          2m31s

NAMESPACE   NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default     deployment.apps/default-http-backend   1         1         1            1           2m31s

NAMESPACE   NAME                                              DESIRED   CURRENT   READY   AGE
default     replicaset.apps/default-http-backend-587b7d64b5   1         1         1       2m31s
```

Now, let's say you create a deployment (microbot), a coresponding service and you want to expose it through ingress.

```
microk8s.kubectl create -f https://raw.githubusercontent.com/ubuntu/microk8s/master/tests/templates/ingress.yaml
```

The ingress rule looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: microbot-ingress
spec:
 rules:
   - host: microbot.127.0.0.1.xip.io
     http:
       paths:
         - path: /
           backend:
             serviceName: microbot
             servicePort: 80
```

You can see the rule created here:
```
> microk8s.kubectl get ingress
NAME               HOSTS                       ADDRESS   PORTS   AGE
microbot-ingress   microbot.127.0.0.1.xip.io             80      44s
```


If you point your browser at http://microbot.127.0.0.1.xip.io/ (or do a wget from the machine on AWS) you should get the microbot.

If you do not get the ingress controller with `microk8s.enable ingress` then something is wrong. Please, attach the logs tarball you will get with `microk8s.inspect` so we can have a better view of what is happening.

Thank you for using microk8s.
