### ISSUE TITLE
Ingress not working on AWS.

### ISSUE THREAD

**Issue by yasiemir** [ubuntu/microk8s#143]
I have a single node setup on AWS ubuntu instance using microk8s with ingress controller enabled by using
`microk8s.enable ingress`. 
Which has added the following service:
```bash
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
default-http-backend   ClusterIP   10.152.183.50   <none>        80/TCP    8m47s
```
and the following deployment: 
```bash
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default-http-backend   1         1         1            1           10m
```
which I belive is the ingress controller.

Now when I try to create the following ingress:
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: nodeserver
    servicePort: 7070
```
The `ADDRESS` is not assigned to the ingress
```bash
kubectl get ingress
NAME            HOSTS   ADDRESS   PORTS   AGE
basic-ingress   *                 80      12m
```
Is there anything specific to AWS loadbalancers that needs to be configured? Or anything that I am missing in the configuration?

I tried installing nginx ingress controller saperately but same issue with that.
