### ISSUE TITLE
Log rotation configuration

### ISSUE THREAD

**Issue by kfirfer** [ubuntu/microk8s#1465]
Hello

I have tried to append this configuration inside `/var/snap/microk8s/current/args/kubelet`:
```
--container-log-max-files=2
--container-log-max-size=10Mi
```

And its seems he respect only the "max-files" parameter and ignoring "max-size"
the "max-size" seems like he always set to 1GB+-

Full config:
```
--kubeconfig=${SNAP_DATA}/credentials/kubelet.config
--cert-dir=${SNAP_DATA}/certs
--client-ca-file=${SNAP_DATA}/certs/ca.crt
--anonymous-auth=false
--network-plugin=cni
--root-dir=${SNAP_COMMON}/var/lib/kubelet
--fail-swap-on=false
--cni-conf-dir=${SNAP_DATA}/args/cni-network/
--cni-bin-dir=${SNAP_DATA}/opt/cni/bin/
--feature-gates=DevicePlugins=true
--eviction-hard="memory.available<100Mi,nodefs.available<1Gi,imagefs.available<1Gi"
--container-runtime=remote
--container-runtime-endpoint=${SNAP_COMMON}/run/containerd.sock
--container-log-max-files=2
--container-log-max-size=10Mi
--containerd=${SNAP_COMMON}/run/containerd.sock
--node-labels="microk8s.io/cluster=true"
--authentication-token-webhook=true
--runtime-cgroups=/systemd/system.slice
--kubelet-cgroups=/systemd/system.slice
--cluster-domain=cluster.local
--cluster-dns=10.152.183.10
```

Reproduce:
Make a simple job that print lots of lines to the stdout:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: logger
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: logger
          image: curlimages/curl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args: ["-c", "for i in `seq 10000000`; do echo 'testestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestesttestestestestestestestestestestestestest'; done"]
      restartPolicy: Never
  backoffLimit: 4
```

[inspection-report-20200801_161839.tar.gz](https://github.com/ubuntu/microk8s/files/5010905/inspection-report-20200801_161839.tar.gz)
