### ISSUE TITLE
multus host-device breaks when StatefulSet restarts a pod

### ISSUE THREAD

**Issue by wknickless** [ubuntu/microk8s#1468]
Under microk8s v1.18.6 rev 1551 there seems to be a race condition when a StatefulSet restarts a pod containing a multus cni host-device.  The network namespace of the old pod doesn't go away, so the host-device isn't available in the default network namespace for multus to put in the new pod.

To replicate, create a veth pair with a known MAC address:

```
$ sudo ip link add name multus0 type veth peer name multus1 address 02:04:06:08:10:12
```

Then apply this YAML with `kubectl apply -f`:

```
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-host-device
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "hwaddr": "02:04:06:08:10:12"
  }'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multus-host-device
  labels:
    app: multus-host-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multus-host-device
  serviceName: multus-host-device
  template:
    metadata:
      labels:
        app: multus-host-device
      annotations:
        k8s.v1.cni.cncf.io/networks: multus-host-device
    spec:
      initContainers:
      - name: linkup
        image: nicolaka/netshoot
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - bash
        - -ce
        - |
          ip link show dev net1
          ip link set up dev net1
          ip link show dev net1
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command:
        - bash
        - -ce
        - |
          while :
          do
            date
            ip link show
            echo
            sleep 30
          done

```

The first pod created by the StatefulSet works fine:

```
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       39s   default-scheduler  Successfully assigned default/multus-host-device-0 to k8s
  Normal  AddedInterface  37s   multus             Add eth0 [10.1.34.187/32]
  Normal  AddedInterface  37s   multus             Add net1 [] from multus-host-device
  Normal  Pulling         37s   kubelet, k8s       Pulling image "nicolaka/netshoot"
  Normal  Pulled          18s   kubelet, k8s       Successfully pulled image "nicolaka/netshoot"
  Normal  Created         18s   kubelet, k8s       Created container linkup
  Normal  Started         17s   kubelet, k8s       Started container linkup
  Normal  Pulling         16s   kubelet, k8s       Pulling image "nicolaka/netshoot"
  Normal  Pulled          4s    kubelet, k8s       Successfully pulled image "nicolaka/netshoot"
  Normal  Created         4s    kubelet, k8s       Created container netshoot
  Normal  Started         4s    kubelet, k8s       Started container netshoot
```

But if you delete the first pod (`kubectl delete pod multus-host-device-0`), the replacement pod doesn't start:

```
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               3s    default-scheduler  Successfully assigned default/multus-host-device-0 to k8s
  Normal   AddedInterface          1s    multus             Add eth0 [10.1.193.116/32]
  Warning  FailedCreatePodSandBox  0s    kubelet, k8s       Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9b2206c730d5857ef656240b105c423d29bc954e8ef3b64969968a7f484c0d05": [default/multus-host-device-0:multus-host-device]: error adding container to network "multus-host-device": failed to find host device: failed to find physical interface
```

Running `sudo ip -all netns exec ip link` will show the interface still in the old network namespace:

```
netns: cni-a399a9b9-bdb4-29b2-075e-6769dbe41e5b
1: lo: <LOOPBACK> mtu 65536 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
291: net1@if292: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN mode DEFAULT group default qlen 1000
    link/ether 02:04:06:08:10:12 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    alias multus1
```

This broken state is persistent until the StatefulSet is deleted (`kubectl delete statefulset multus-host-device`).  After the StatefulSet is deleted it can take 30 seconds or so for the original pod's network namespace to disappear.

Note that when you delete the StatefulSet the veth pair will also be deleted.  My actual use case is to run zeek, a network intrusion detector, against a physical network interface.  Fortunately the physical interface doesn't get deleted when the StatefulSet gets deleted!

[inspection-report-20200804_004615.tar.gz](https://github.com/ubuntu/microk8s/files/5019576/inspection-report-20200804_004615.tar.gz)
