### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by wmentzel** [ubuntu/microk8s#1485]
I am trying to apply this deployment:

`microk8s kubectl apply -f https://raw.githubusercontent.com/nats-io/k8s/master/nats-streaming-server/single-server-stan.yml`

```
...
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: "Filesystem"
      resources:
        requests:
          storage: 1Gi
...
```

from [here](https://docs.nats.io/nats-on-kubernetes/minimal-setup). but it fails with

> running "VolumeBinding" filter plugin for pod "stan-0": pod has unbound immediate PersistentVolumeClaims

I already ran:

`microk8s enable storage`

because it was disabled before.

`microk8s kubectl get storageclass` returns

> NAME                          PROVISIONER            RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
> microk8s-hostpath (default)   microk8s.io/hostpath   Delete          Immediate           false                  91m

`microk8s inspect` tarball:

[inspection-report-20200813_133328.tar.gz](https://github.com/ubuntu/microk8s/files/5068744/inspection-report-20200813_133328.tar.gz)

I suspect that it is microk8s related, because colleagues of mine were able to apply the deployment using minikube.
