### ISSUE TITLE
docker.d location

### ISSUE THREAD

**Issue by mgonzaga1990** [ubuntu/microk8s#1487]
I'm just new to microk8s and would like to ask one question.

So I was setting up ```registry``` in my kubernetes cluster running on my raspberry pi and part of the configuration is to set up ```insecure-registries```. However, I don't have docker installd on my machine as I have heard from my collegue that micok8s has some sort of docker daemon inside.

Since I have no ```docker``` installed on my machine therefore I have no ```/var/lib/daemon.json```. But luckily my reasearch bought me in this issue https://github.com/ubuntu/microk8s/issues/384. There i learned that I could do the same thing by modifiying this file ```/var/snap/microk8s/current/args/containerd-template.toml```

now I would like to find the simillar approach but this time I would like to find where this file ```/var/run/docker.sock``` located. As I need it in my ```drone ci```

As of now on my drone ci I'm just doing a side car on this image ```docker.io/library/docker:18.06-dind```  to get the same effect 
but it is giving me this below error.

```
time="2020-08-13T19:38:35Z" level=trace msg="http: no content returned: re-connect and re-try"
time="2020-08-13T19:38:46Z" level=trace msg="http: no content returned: re-connect and re-try"
```
sometimes it works but most of the time it dosen't

by the way i'm using 1.8

**Comment by ktsakalozos** [comment]
I suspect you are looking for the container runtime endpoint in `/var/snap/microk8s/common/run/containerd.sock`?

**Comment by mgonzaga1990** [comment]
I'm not sure but according to docs of drone ci

https://docs.drone.io/runner/docker/installation/linux/

it is mounting to /var/run/docker.sock

anyway i'll try that and let you know the result.

thanks

**Comment by mgonzaga1990** [comment]
Hi @ktsakalozos , 

Here is the set up I tried.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-runner-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/snap/microk8s/common/run/containerd.sock"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-runner-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drone-runner
  labels:
    app: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
        - name: drone-runner
          image: 'drone/drone-runner-docker:1'
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DRONE_RPC_HOST
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_SERVER_HOST
            - name: DRONE_RPC_PROTO
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_SERVER_PROTO
            - name: DRONE_RPC_SECRET
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_RPC_SECRET
            - name: DRONE_RUNNER_CAPACITY
              value: '2'
            - name: DRONE_LOGS_TRACE
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_LOGS_TRACE
            - name: DRONE_LOGS_PRETTY
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_LOGS_PRETTY
            - name: DRONE_LOGS_COLOR
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: DRONE_LOGS_COLOR
          volumeMounts:
            - name: docker-runner-storage
              mountPath: /var/run/docker.sock
      volumes:
      - name: docker-runner-storage
        persistentVolumeClaim:
            claimName: drone-runner-pvc 
```


Here i'm mounting ```drone``` path ```/var/run/docker.sock``` to ```/var/snap/microk8s/common/run/containerd.sock```

But on the log there result is this
```
time="2020-08-14T10:41:23Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:24Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:25Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:26Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:27Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:28Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
time="2020-08-14T10:41:29Z" level=error msg="cannot ping the docker daemon" error="Get http://%2Fvar%2Frun%2Fdocker.sock/_ping: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x00\\x04\\x00\\x00\\x00\\x00\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"
```

**microk8s inspect**
```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```
