### ISSUE TITLE
error: error validating "microing.yaml": error validating data: ValidationError(DaemonSet.spec.selector): unknown field "name" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector;

### ISSUE THREAD

**Issue by AnishAnil** [ubuntu/microk8s#1500]
Hello Microk8s

I'm trying to expose a custom ssh port that will be used for connecting and cloning the git repo.

Ex: Command that i run:

git clone ssh://aanil@androidhubgit.com:29418/All-Projects

If i create a nodeport and change it to 30000 and then run a clone it works perfectly.
However we cannot expose 30000  and it needs to be 29418.

I went through the documentation and found the following link:

https://microk8s.io/docs/addon-ingress

I created a secret with the below yaml file.
````
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  29418: "default/gerrit-service:29418"
````
******************* This works without any errors and i can see the config maps***********************
My deployment yaml file
**************************************
````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-deployment
  labels:
    app: gerrit-meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
      type: frontend
  template:
    metadata:
      labels:
        app: gerrit
        type: frontend
    spec:
      containers:
      - name: gerrit
        image: gerritcodereview/gerrit
        env:
          - name: CANONICAL_WEB_URL
            value: https://ec2-18-219-145-189.us-east-2.compute.amazonaws.com
        ports:
         - containerPort: 8080
         - containerPort: 29418
````
**************************************This also goes through as expected********************
**************************************My Service file**************************************
````
apiVersion: v1
kind: Service
metadata:
  name: gerrit-service
  labels:
      app: gerrit
      type: frontend
spec:
  ports:
  - name: 1http
    port: 8080
    protocol: TCP
  - name: sshcon
    port: 29418
    protocol: TCP
  selector:
      app: gerrit
      type: frontend
````
***************************This also works as expected and creates the service

Now i want to expose the tcp/udp port for 29418 so as per the document i created a new ingress file
*****************************
````
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    microk8s: gerritingress
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  selector:
    name: gerrit
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        -
          image: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.25.1"
          name: nginx-ingress-microk8s
          ports:
            -
              containerPort: 80
            -
              containerPort: 443
            -
              containerPort: 29418
              hostPort: 29418
              name: tcp-29418
              protocol: TCP
````
***********************************************************************

The instance I apply this file it errors out with

kubectl apply -f microing.yaml
error: error validating "microing.yaml": error validating data: ValidationError(DaemonSet.spec.selector): unknown field "name" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false

I tried different approach and all of them fails with similar errors.

Why am i getting this error.
Is this the correct approach to expose port 29418
Is there something wrong with the documentation as it fails and i somehow feel this is a defect or less tested.

Kindly guide on how to fix this issue.
This is almost like a deal breaker for our setup and i would like to get this fixed or understand the right approch

Thank you,
Anish

**Comment by balchua** [comment]
@AnishAnil it will be great if you can format your relevant manifests using markdown code blocks.
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

First question, did u use `microk8s enable ingress`? It seems like you are trying to install your own ingress.

**Comment by balchua** [comment]
Related to https://github.com/ubuntu/microk8s/issues/1471

**Comment by balchua** [comment]
@AnishAnil your `DaemonSet` definition is not correct. Try this.

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
  labels:
      microk8s: gerritingress
spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - containerPort: 80
        - containerPort: 443
        - name: nginx-ingress-tcp-microk8s-conf
          containerPort: 29418
          hostPort: 29418
          protocol: TCP
```

**Comment by AnishAnil** [comment]
> 
> 
> @AnishAnil it will be great if you can format your relevant manifests using markdown code blocks.
> https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks
> 
> First question, did u use `microk8s enable ingress`? It seems like you are trying to install your own ingress.

Yes, it is done.

````
root@ip-172-31-47-59:~# microk8s status
microk8s is running
addons:
dashboard: enabled
dns: enabled
ingress: enabled
registry: enabled
storage: enabled
cilium: disabled
fluentd: disabled
gpu: disabled
helm: disabled
helm3: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: disabled

````

**Comment by AnishAnil** [comment]
> 
> 
> @AnishAnil your `DaemonSet` definition is not correct. Try this.
> 
> ```yaml
> apiVersion: apps/v1
> kind: DaemonSet
> metadata:
>   name: nginx-ingress-microk8s-controller
>   namespace: ingress
>   labels:
>       microk8s: gerritingress
> spec:
>   template:
>     spec:
>       containers:
>       - name: nginx-ingress-microk8s
>         ports:
>         - containerPort: 80
>         - containerPort: 443
>         - name: nginx-ingress-tcp-microk8s-conf
>           containerPort: 29418
>           hostPort: 29418
>           protocol: TCP
> ```

I had tried the same data that you suggested as it was part of the documentation and it had errored out and hence used the new 
yaml file. 
````
kubectl apply -f ingress.yaml
error: error validating "ingress.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```` 
NOTE: I'm not trying to use an external ingress, Rather making use of the one provided in microK8s as  we want to really understand how the functionality is working as compared to other Kubernetes products and are staying and using native solution provided in micro K8s

**Comment by balchua** [comment]
`DaemonSet` doesn't have `spec.selector.name` that is what the error says.
Do you also mind pointing us what error you get when you use the manifest file as mentioned in the documentation of microk8s? Thanks

**Comment by AnishAnil** [comment]
@balchua,

````
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  6379: "default/redis:6379"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
spec:
  template:
    spec:
      containers:
      - name: nginx-ingress-microk8s
        ports:
        - containerPort: 80
        - containerPort: 443
        - name: proxied-tcp-6379
          containerPort: 6379
          hostPort: 6379
          protocol: TCP

````
kubectl apply -f microk8singress.yaml
error: error validating "microk8singress.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by ktsakalozos** [comment]
I think you are also missing a seletor. You can find more information on the Daemonset manifest in [1]

[1] https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

**Comment by balchua** [comment]
@ktsakalozos i think we should also update our docs to reflect the valid yaml.

**Comment by AnishAnil** [comment]
Is there a file that you can share, I tested several combinations but it fails with "name" attribute which it looks to be fetching from ur code. Kindly help understand the exact attribute that is failing

**Comment by AnishAnil** [comment]
Further the yaml shared in the example with "- name: **proxied-tcp-6379**" also failed with the length and it needs to be reduced.

**Comment by balchua** [comment]
Check the link provided above regarding daemonset.  You can also check the microk8s ingress file and how the daemonset is defined.

https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml

**Comment by balchua** [comment]
I think the existing manifest provided in the docs are not meant to be used with `kubectl apply` instead a `kubectl patch`. You need to edit the current running ingress daemonset.
Thats about it.

**Comment by AnishAnil** [comment]
````
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
  labels:
    microk8s-application: nginx-ingress-microk8s
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      containers:
      - name: nginx-ingress-microk8s
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.25.1
        ports: 
        - containerPort: 80
        - containerPort: 443
        - name: tcp-28419
          containerPort: 28419
          hostPort: 28419
          protocol: TCP
````

It now fails with the below errors:

````
root@ip-172-31-47-59:~/files# kubectl logs nginx-ingress-microk8s-controller-7blqz -n ingress
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       0.25.1
  Build:         git-5179893a9
  Repository:    https://github.com/kubernetes/ingress-nginx/
  nginx version: openresty/1.15.8.1

-------------------------------------------------------------------------------
W0820 15:24:22.424399       7 flags.go:221] SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)

nginx version: openresty/1.15.8.1
W0820 15:24:22.442041       7 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0820 15:24:22.442294       7 main.go:183] Creating API client for https://10.152.183.1:443
I0820 15:24:22.472919       7 main.go:227] Running in Kubernetes cluster version v1.18 (v1.18.6) - git (clean) commit dff82dc0de47299ab66c83c626e08b245ab19037 - platform linux/amd64
I0820 15:24:22.785365       7 main.go:102] Created fake certificate with PemFileName: /etc/ingress-controller/ssl/default-fake-certificate.pem
F0820 15:24:22.790553       7 nginx.go:126] unexpected error obtaining pod information: unable to get POD information (missing POD_NAME or POD_NAMESPACE environment variable

````

**Comment by AnishAnil** [comment]
> @balchua 
> 
> Check the link provided above regarding daemonset. You can also check the microk8s ingress file and how the daemonset is defined.
> 
> https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml

I used the yaml file provided in the link, since using only an excerpt gave other errors,

This time it failed with the below errors:

````
kubectl apply -f ingress2.yaml
namespace/ingress unchanged
serviceaccount/nginx-ingress-microk8s-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/nginx-ingress-microk8s-clusterrole unchanged
role.rbac.authorization.k8s.io/nginx-ingress-microk8s-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s unchanged
configmap/nginx-load-balancer-microk8s-conf unchanged
configmap/nginx-ingress-tcp-microk8s-conf unchanged
configmap/nginx-ingress-udp-microk8s-conf unchanged
error: error parsing ingress2.yaml: error converting YAML to JSON: yaml: line 56: could not find expected ':'
````
I see that the file provided in a yaml editor and it looks good though. 

Can we raise this as a defect or fix the documentation on how to deploy the ingress for custom ports.

**Comment by AnishAnil** [comment]
> 
> 
> I think the existing manifest provided in the docs are not meant to be used with `kubectl apply` instead a `kubectl patch`. You need to edit the current running ingress daemonset.
> Thats about it.

root@ip-172-31-47-59:~/files# kubectl patch -f ingress3.yaml
Error: required flag(s) "patch" not set

The command never runs

**Comment by balchua** [comment]
@AnishAnil i didn't mean that you run the whole ingress definition that you see in the microk8s source. It came with the role definitions that you do not need to rerun.
Let's bring back the ingress controller to its correct form.
`microk8s disable ingress` followed by `microk8s enable ingress`.
Now lets edit the `nginx-ingress-tcp-microk8s-conf`.
* To edit the `ConfigMap` do `microk8s kubectl edit cm nginx-ingress-tcp-microk8s-conf` and add the port you want to expose. `29418: "default/gerrit-service:29418"`
* Then edit the `DaemonSet` by adding the port you want the ingress to expose at the `spec.template.container` section using `microk8s kubectl edit ds nginx-ingress-microk8s-controller`
```yaml
     - name: ssh-29418
          containerPort: 29418
          hostPort: 29418
          protocol: TCP
```
Be careful with the spaces. Yaml is very picky with that.
Fyi i haven't tried this.  Will need your help to debug this yourself if you are running into yaml issues.  MicroK8s is not changing the behavior of the ingress controller.  It is taken from the upstream nginx ingress controller.
