### ISSUE TITLE
DNS resolution fails on all but one node 

### ISSUE THREAD

**Issue by pschmitt** [ubuntu/microk8s#1504]
### Description

I run a 3 node cluster and have installed the HA tech preview like so:

```bash
sudo snap install microk8s --classic --channel=latest/edge/ha-preview
```

After having the nodes join the cluster with the join token obtained with `microk8s add-node -l -1` on node 1 and enabling the DNS addon with `microk8s enable dns` I noticed that all pods scheduled to run on nodes 2 and 3 are unable to do DNS resolution.

I've tried restarting the services, the nodes, resetting, uninstalling + resetting etc.
All pods running on the first node work as expected. There's no apparent issue when running `microks inspect`.

The only odd thing about my setup is that node 3 is a Raspberry Pi 4 on Ubuntu 20.04 (ARM64) while nodes 1 and 2 are bog-standard AMD64 hosts (Fedora Server 32). But the issue happens for both one of the AMD64 and the ARM64 host.

#### Test procedure

To test this issue I pinned a pod to a specific host with the following (example for "node 3"):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-deleteme-pi48
  labels:
    env: test
spec:
  containers:
  - name: test
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
  nodeSelector:
    kubernetes.io/hostname: pi48
```

#### microk8s inspect

Node 1:
[inspection-report-20200820_115425.tar.gz](https://github.com/ubuntu/microk8s/files/5102153/inspection-report-20200820_115425.tar.gz)

Node 2:
[inspection-report-20200820_115522.tar.gz](https://github.com/ubuntu/microk8s/files/5102164/inspection-report-20200820_115522.tar.gz)

Node 3:
[inspection-report-20200820_115633.tar.gz](https://github.com/ubuntu/microk8s/files/5102159/inspection-report-20200820_115633.tar.gz)
