### ISSUE TITLE
Prometheus RBAC For Other Namespaces

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1522]
I needed to add this to allow prometheus to use service monitors in other namespaces. If anyone else has this problem here is an option:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-cluster
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s-cluster
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
```
