### ISSUE TITLE
Microk8s is not applying docker.io mirror changes

### ISSUE THREAD

**Issue by whiskerch** [ubuntu/microk8s#1525]
Hi,

I'm trying to change microk8s to use an internal mirror of docker hub to pull all images through, but it does not seem to apply the changes in the configuration I have made. 

I am using a Sonatype/Nexus3 docker proxy to cache images we are using, and need to get microk8s to pull images from there instead of going direct to the https://registry-1.docker.io url

To do this I have modified the file at `/var/snap/microk8s/current/args/containerd-template.toml` and have changed this entry:

```
[plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["https://registry-1.docker.io"]
```
to
```
[plugins.cri.registry.mirrors."docker.io"]
    endpoint = ["https://my-mirror.xxxxxxxx.com"]
```

I have then stopped and started the microk8s service (and can see the changes reflected in `/var/snap/microk8s/current/args/containerd.toml`

However, when I deploy Istio with the `microk8s.enable istio` command, and then look at the pods, I can see messages such as: 

```
Failed to pull image "docker.io/istio/citadel/manifests/1.3.4": rpc error: code = Unknown desc = failed to resolve image "docker.io/istio/citadel/manifests/1.3.4": no available registry endpoint: failed to do request: Head "https://registry-1.docker.io/v2/istio/citadel/manifests/1.3.4" dial txp x.x.x.x:443: connect: connection refused
```
(I have blocked the docker.io on our infrastructure to make sure it was using the proxy)

However...

On the same box with docker I have this config in the daemon.json file: 
```
{
    "registry-mirrors":["https://my-mirror.xxxxxxxx.com"]
}
```

If I run the command: 
```
docker pull istio/citadel:1.3.4
```
It is able to use my mirror without any issue. 

Is there anything I am missing when it comes to telling microk8s where to look for docker.io based images? 

Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20200828_124323.tar.gz](https://github.com/ubuntu/microk8s/files/5142099/inspection-report-20200828_124323.tar.gz)

**Comment by whiskerch** [comment]
I think this issue could be the cause of my problems: https://github.com/containerd/containerd/issues/4011

**Comment by hjanuschka** [comment]
same problem here.... can't get it to work.
need to get rid of docker.hub, because of the pull limit.
we run a harbor as mirror/proxy  - but microk8s doesnt use it :'(


<img width="1192" alt="Bildschirmfoto 2020-12-02 um 11 18 17" src="https://user-images.githubusercontent.com/2891702/100859870-165c1300-3490-11eb-805d-0d0aee5aa0e4.png">

**Comment by patsevanton** [comment]
Any news?

**Comment by franco-caylent** [comment]
Im having the same issue. There are no clear docs on how to configure it. I'm trying to use the internal registry as a cache. It works with docker, but microk8s ignores it.
I have the default config in containerd-template.toml
```  
[plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "${SNAP_DATA}/args/certs.d"
   ```
/var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml
     
```
server = "https://docker.io"

[host."http://localhost:32000"]
  capabilities = ["pull", "resolve"]
   ```
I have an overwrite in the hosts file for registry-1.docker.io and I'm using the following command for testing
   ` microk8s ctr image pull docker.io/rclone/rclone:1.50 `
  And the output is always
` error="failed to do request: Head \"https://registry-1.docker.io/... `

Sources I've been checking:
https://github.com/containerd/containerd/blob/main/docs/cri/config.md#registry-configuration
https://microk8s.io/docs/registry-private ( I've tried localhost:32000 without HTTP and doesn't work either)

Im running micrk8s v1.23.5 on ubuntu 20.04.4

**Comment by franco-caylent** [comment]
Im having the same issue, tracking progress in https://github.com/containerd/containerd/issues/4011

**Comment by pweibert** [comment]
I still have this issue with MicroK8s v1.30.3 revision 7040
this is my `/var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml`
```
server = "https://registry-1.docker.io"

[host."http://localhost:32000"]
  capabilities = ["pull", "resolve"]
```
I've also tried to apply a launch config in `/var/snap/microk8s/common/.microk8s.yaml`:
```
# microk8s-config.yaml
---
version: 0.1.0
addons:
  - name: dns
  - name: nvidia
#  - name: rbac
#  - name: ingress
#  - name: hostpath-storage
  - name: registry

# The extra arguments listed here are not required, as they would be set by the 'rbac' and the 'dns'
# addons respectively. However, we set them to save time by not having to restart the Kubernetes
# services a few times during cluster bootstrap.
extraKubeAPIServerArgs:
  --authorization-mode: RBAC,Node
extraKubeletArgs:
  --cluster-dns: 10.152.183.10
  --cluster-domain: cluster.local

containerdRegistryConfigs:
  # Use `http://my.proxy:5000` as a DockerHub registry mirror.
  docker.io: |
    [host."localhost:32000"]
    capabilities = ["pull", "resolve"]
```
This is what I get when I try to pull the image (I've disabled the internet access for my box in router settings, no connection to external network)

microk8s ctr images pull docker.io/postgres:10.4 --htt[sudo] password for usercmr: 
INFO[0000] HEAD /v2/postgres/manifests/10.4 HTTP/1.1    
INFO[0000] Host: registry-1.docker.io                   
INFO[0000] Accept: application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distrv1+json, */* 
INFO[0000] User-Agent: containerd/v1.6.28               
INFO[0000]                                              
INFO[0000] trying next host                              error="failed to do request: Head \"https://server misbehaving" host=registry-1.docker.io
ctr: failed to resolve reference "docker.io/postgres:10.4": failed to do request: Head "https://regis misbehaving

While this works:
microk8s ctr images pull localhost:32000/postgres:10.4 --http-dump
