### ISSUE TITLE
Changing network from WIFI to LAN microk8s network breaks

### ISSUE THREAD

**Issue by belsakn** [ubuntu/microk8s#1544]
Hey, I'm having this problem when I change the network from WIFI to LAN cilium and DNS pods stop working.
The cilium-operator pod can't connect create k8s client `kubectl -n kube-system logs cilium-operator`:
```
level=error msg="Unable to contact k8s api-server" error="Get https://10.152.183.1:443/api/v1/namespaces/kube-system: dial tcp 10.152.183.1:443: connect: no route to host" ipAddr="https://10.152.183.1:443" subsys=k8s
level=fatal msg="Unable to connect to Kubernetes apiserver" error="unable to create k8s client: unable to create k8s client: Get https://10.152.183.1:443/api/v1/namespaces/kube-system: dial tcp 10.152.183.1:443: connect: no route to host" subsys=cilium-operator
```
I found out that the cluster IP is changing:
`microk8s.config` On WIFI:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://192.168.8.102:16443 <-- HERE
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: ...
```
`microk8s.config` On LAN:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://192.168.8.103:16443 <-- HERE
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: ...
```
All good, but the Endpoint in default Kubernetes svc is not changing `kubectl describe svc kubernetes`:
```
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.152.183.1
Port:              https  443/TCP
TargetPort:        16443/TCP
Endpoints:         192.168.8.103:16443 <-- HERE
Session Affinity:  None
Events:            <none>
```
Does someone know how can I fix this problem?
