### ISSUE TITLE
enable storage failed

### ISSUE THREAD

**Issue by github1youlc** [ubuntu/microk8s#1557]
Failed to execute `microk8s enable storage`
Output is as follows 

```
Enabling default storage class. 
sudo: unable to dlopen /usr/libexec/sudoers.so: (null). 
sudo: fatal error, unable to load plugins. 
Failed to enable storage
```

I have made sure that the sudoer.so library can be loaded using dlopen in c++ and the sudo command works fine.

Wish for your help!!!

[inspection-report-20200913_234014.tar.gz](https://github.com/ubuntu/microk8s/files/5214465/inspection-report-20200913_234014.tar.gz)

**Comment by balchua** [comment]
There are other issues in the log.
For example:
```shell
Sep 12 08:42:09 localhost microk8s.daemon-proxy[15883]: W0912 08:42:09.562833   15883 iptables.go:550] Could not set up iptables canary nat/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
```
Do you want to tell us more about the OS?

And can you reboot the system?

**Comment by tencent-attribution** [comment]
> Thanks for using MicroK8s. I find that There are other issues in the log. Most especially `kube-proxy`.
> 
> For example:
> 
> ```shell
> Sep 12 08:42:09 localhost microk8s.daemon-proxy[15883]: W0912 08:42:09.562833   15883 iptables.go:550] Could not set up iptables canary nat/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
> ```
> 
> Do you want to tell us more about the OS?
> 
> And can you reboot the system?

That error occured when `microk8s enable dns`, I have solved the problem by installing the `nat` library.  
    
  
OS is based on centos, but there are some customization by my company.
```
cat /etc/centos-release
CentOS Linux release 7.2 (Final) 
```


After rebooting the system, I still can not enable storage.

**Comment by github1youlc** [comment]
> Thanks for using MicroK8s. I find that There are other issues in the log. Most especially `kube-proxy`.
> 
> For example:
> 
> ```shell
> Sep 12 08:42:09 localhost microk8s.daemon-proxy[15883]: W0912 08:42:09.562833   15883 iptables.go:550] Could not set up iptables canary nat/KUBE-PROXY-CANARY: error creating chain "KUBE-PROXY-CANARY": exit status 3: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
> ```
> 
> Do you want to tell us more about the OS?
> 
> And can you reboot the system?

That error occured when executing `microk8s enable dns`, I have solved the problem by installing the `nat` library.

OS is based on centos, but there are some customization by my company.
```
cat /etc/centos-release
CentOS Linux release 7.2 (Final) 
```

After rebooting the system, I still can not enable storage.

**Comment by balchua** [comment]
Just wanted to try this.  Can you do `microk8s enable helm3`, just to see if you also get the same issue.
Thanks

**Comment by github1youlc** [comment]
> Just wanted to try this. Can you do `microk8s enable helm3`, just to see if you also get the same issue.
> Thanks

It works. And I can use it to install helm charts.

**Comment by balchua** [comment]
Ok thanks. I think the script `enable-storage.sh` isn't taking the system `LD_LIBRARY_PATH` like it is done for other enable script.

The `enable-storage.sh` should be using this [1], instead of just calling `sudo`.
Thanks for reporting this.

For the meantime, to enable the storage,
Create the directory where the hostpath will keep the images.

```shell
$ sudo mkdir -p /var/snap/microk8s/common/default-storage
```
 Then apply the manifest below.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner
  labels:
    k8s-app: hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: hostpath-provisioner
  template:
    metadata:
      labels:
        k8s-app: hostpath-provisioner
    spec:
      serviceAccountName: microk8s-hostpath
      containers:
        - name: hostpath-provisioner
          image: cdkbot/hostpath-provisioner-amd64:1.0.0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PV_DIR
              value: /var/snap/microk8s/common/default-storage
          volumeMounts:
            - name: pv-volume
              mountPath: /var/snap/microk8s/common/default-storage
      volumes:
        - name: pv-volume
          hostPath:
            path: /var/snap/microk8s/common/default-storage
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microk8s-hostpath
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8s-hostpath
rules:
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - list
  - get
  - update
  - watch
  - create
  - delete
- apiGroups: [""]
  resources:
    - events
  verbs:
    - create
    - list
    - patch
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
  verbs:
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: microk8s-hostpath
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: microk8s-hostpath
subjects:
  - kind: ServiceAccount
    name: microk8s-hostpath
    namespace: kube-system
```

[1] https://github.com/ubuntu/microk8s/blob/22a970b03a7b24ff8f733d5a91475a1babcb323a/microk8s-resources/actions/common/utils.sh#L70
