### ISSUE TITLE
Error: cannot change profile for the next exec call: No such file or directory

### ISSUE THREAD

**Issue by a-hahn** [ubuntu/microk8s#1643]
Host is Ubuntu 20.04
I have installed microk8s 1.19 in an lxc container with Ubuntu 20.04 -- worked ok
I have reconfigured the host interface as a bridge so that container can be reached from the local net - worked ok.
I reconfigured the host interface and removed the bridge. That did not work with the same profile as expected.
Then I reconfigured the host interface as a bridge again. 
Now the microk8s container does not work anymore:
`lxc exec container -- bash` then:
```
root@homekube:~# microk8s.inspect
cannot change profile for the next exec call: No such file or directory
```
Not sure whether this is a problem with netplan | lxc | microk8s ?

Restoring a formerly saved snapshot of the container does not solve the problem.

Host config

1) `cat /etc/netplan/10-bridge-config-for-lxd-homekube.yaml`
```
network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s10:
            dhcp4: yes
    bridges:
      br0:
        dhcp4: yes
        interfaces: [enp0s10]
```
2) `ip a s`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s10: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 00:26:2d:2d:2f:2f brd ff:ff:ff:ff:ff:ff
3: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:26:2d:2d:2f:2f brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.90/16 brd 192.168.255.255 scope global dynamic br0
       valid_lft 84961sec preferred_lft 84961sec
    inet6 fe80::48af:ecff:fea3:c1ee/64 scope link 
       valid_lft forever preferred_lft forever
5: veth8dd99ab0@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
    link/ether ea:c0:ae:f8:a3:2f brd ff:ff:ff:ff:ff:ff link-netnsid 0
```
3) `lxc list`
```
+----------+---------+---------------------+------+-----------+-----------+
|   NAME   |  STATE  |        IPV4         | IPV6 |   TYPE    | SNAPSHOTS |
+----------+---------+---------------------+------+-----------+-----------+
| homekube | RUNNING | 192.168.1.99 (eth0) |      | CONTAINER | 1         |
+----------+---------+---------------------+------+-----------+-----------+
| ubuntu1  | STOPPED |                     |      | CONTAINER | 0         |
+----------+---------+---------------------+------+-----------+-----------+
| ubuntu2  | STOPPED |                     |      | CONTAINER | 0         |
+----------+---------+---------------------+------+-----------+-----------+
```
4) `lxc profile show microk8s`
```
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw cgroup:rw
    lxc.cgroup.devices.allow=a
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /sys/module/nf_conntrack/parameters/hashsize
    type: disk
  aadisable1:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
  aadisable2:
    path: /dev/kmsg
    source: /dev/kmsg
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: microk8s
used_by:
- /1.0/instances/homekube
```
