### ISSUE TITLE
Segfault when installing via snap

### ISSUE THREAD

**Issue by joshbranham** [ubuntu/microk8s#1724]
When using `cloud-init` and a shell script to install microk8s on Ubuntu 18.04, we see a segfault issue sometimes. It is hard to pin down, but we are running `snap install microk8s --channel=1.19/edge --classic` and then get:

`cloud-init[1845]: - Run install hook of "microk8s" snap if present (run hook "install": signal: segmentation fault)`

`snapd[2512]: taskrunner.go:271: [change 5 "Run install hook of \"microk8s\" snap if present" task] failed: run hook "install": signal: segmentation fault`

If I jump on the box and try and install it myself, it always works manually after failing in cloud init. Unsure if anyone else has seen this failure?

**Comment by balchua** [comment]
@joshbranham im also using cloud-init but didn't experience the segmentation fault.
What i do experience is that the snap installation get stuck.  It doesn't happen very often though.  So i just destroy and redo.
I also have to admit that i didn't check the logs.

If it helps this is how the `cloud-config` looks like.

```
#cloud-config
package_update: true
packages:
- nfs-kernel-server
- bridge-utils

snap:
    commands:
        00: snap install microk8s --channel=${microk8s_channel} --classic
```
