### ISSUE TITLE
Edits to Prometheus stateful set are overridden!?

### ISSUE THREAD

**Issue by kquinsland** [ubuntu/microk8s#1760]
I have deployed the `monitoring` addon and am now trying to make two changes to prometheus:

1. Enable persistence. I'd like to store Prometheus data to a Persistent Volume so I have historical data going back longer than the average pod lifespan.

2. Adjust the `web.route-prefix=` value to signal that prometheus web interface is exposed behind a proxy. I have a single hostname that i'd like to use for multiple monitoring services. E.G.: `eyes.my-cluster.com/{prometheus, grafana, alerts}` 

TO achieve either, I need to adjust the `prometheus` container.  After running `microk8s enable monitoring` I see that:

- `pod/prometheus-k8s-0` is controlled by `statefulset/prometheus-k8s`
- `statefulset/prometheus-k8s` has a few containers, one of which is `prometheus`.

When i `describe`, i get:

```yaml
      containers:
        - name: prometheus
          image: 'quay.io/prometheus/prometheus:v2.20.0'
          args:
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--config.file=/etc/prometheus/config_out/prometheus.env.yaml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=24h'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.no-lockfile'
            - '--web.route-prefix=/'
    
    <...SNIP...>

        - name: prometheus-config-reloader
          image: 'quay.io/coreos/prometheus-config-reloader:v0.40.0'
          command:
            - /bin/prometheus-config-reloader
          args:
            - '--log-format=logfmt'
            - '--reload-url=http://localhost:9090/-/reload'
            - '--config-file=/etc/prometheus/config/prometheus.yaml.gz'
            - >-
              --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
```

I should be able to edit this yaml file and adjust the values in `containers.prometheus.args` but they are reverted within several seconds. My question is by what/who?

I can see that the `/etc/prometheus/config/prometheus.yaml.gz` file created from a secret:
```yaml

      volumes:
        - name: config
          secret:
            secretName: prometheus-k8s
            defaultMode: 420

```

But when i extract that secret, it's just a YAML file that defines Prometheus scrape jobs. SO that's not it...

When i describe the deployment, I see the 'familiar' `prometheus-config-reloader`, but as explained above, that container really only seems to be concerned with the yaml file that describes the scrape jobs. I do have scrape jobs i want to add, but i'll worry about that _after_ I have the basic two goals described.

```bash

kubectl -n monitoring describe deployment/prometheus-operator 

Name:                   prometheus-operator
Namespace:              monitoring
CreationTimestamp:      Sun, 15 Nov 2020 17:43:25 -0800
Labels:                 app.kubernetes.io/component=controller
                        app.kubernetes.io/name=prometheus-operator
                        app.kubernetes.io/version=v0.40.0
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/name=prometheus-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=controller
                    app.kubernetes.io/name=prometheus-operator
                    app.kubernetes.io/version=v0.40.0
  Service Account:  prometheus-operator
  Containers:
   prometheus-operator:
    Image:      quay.io/coreos/prometheus-operator:v0.40.0
    Port:       8080/TCP
    Host Port:  0/TCP
    Args:
      --kubelet-service=kube-system/kubelet
      --logtostderr=true
      --config-reloader-image=jimmidyson/configmap-reload:v0.3.0
      --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.40.0
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:       <none>
   kube-rbac-proxy:
    Image:      quay.io/coreos/kube-rbac-proxy:v0.4.1
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --logtostderr
      --secure-listen-address=:8443
      --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      --upstream=http://127.0.0.1:8080/
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   prometheus-operator-5b7946f4d6 (1/1 replicas created)
Events:          <none>
```

I know that the prometheus addon is using the [`kube-prometheus`](https://github.com/prometheus-operator/kube-prometheus/blob/master/README.md) operator, but i am struggling to figure out how to enable persistent storage.

Can somebody tell me what I'm missing? Why is `kubectl -n monitoring edit statefulsets/prometheus-k8s` not persisting my changes!?

**EDIT**: Forgot to mention. This is a 6 node cluster with each of the 6 nodes running `v1.19.3-34+a56971609ff35a` via the stable channel

**Comment by balchua** [comment]
Perhaps creating a new `Prometheus` object can help.
According to the prometheus operator api [here](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) do have option to attach volume.

**Comment by kquinsland** [comment]
Thanks for the tip, @balchua.

It took a bit of work, but I've managed to get persistence and custom scrape configs. Below is a slightly edited version of what came from my notes:

------


### Deploy custom scrapers


The ['official'](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/additional-scrape-config.md) documents on this are a bit out of date, but they're still useful. 

0. Make a `prometheus-additional-scrape-jobs.yaml` that has _all_ of your custom scrape jobs in it.

```bash
$ cat prometheus-additional-scrape-jobs.yaml
- job_name: "monitor_something"
  static_configs:
    - targets: ["something_IPAddr:9090"]
```

1. Turn that file into a generic secret called `additional-scrape-configs`

```bash
kubectl -n monitoring create secret generic additional-scrape-configs --from-file=prometheus-additional-scrape-jobs.yaml
secret/additional-scrape-configs created
```

2. Adjust the Prometheus operator to consume the additional scrape targets

```bash
$ kubectl -n monitoring edit prometheuses/k8s
# $EDITOR opens, added this under spec:
#   additionalScrapeConfigs:
#     name: additional-scrape-configs
#     key: prometheus-additional-scrape-jobs.yaml
prometheus.monitoring.coreos.com/k8s edited
```

The 'simplest' way to get the prometheus pod to pick up the new scrape targets is to simply delete it. A new pod will be provisioned within a few seconds.

Use the web ui to confirm that the new target is 'picked up':

```bash
# After running, open http://localhost:9090/targets in a browser and you should see your custom scrape targets
$ kubectl port-forward -n monitoring prometheus-k8s-0 9090:9090

```


## Add Persistance.

The workflow is similar, but comes with a small complication;: we need to [`pause`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) the operator and delete the underlying StatefulSet before making changes to the `storage` configuration. 

I have some 'unique' storage systems set up in my network so the storage class `MyCustomStorageClassHere` is used, but the `Manual storage provisioning` section of the [`storage.md`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md#manual-storage-provisioning) has an alternative `volumeClaimTemplate` for manually allocated persistent volumes if that's more applicable to your needs.

```yaml
spec:
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: MyCustomStorageClassHere
        resources:
          requests:
            storage: 10Gi
```

So with that in mind, the steps to be taken are:

```bash
# Edit spec: and add a paused: true field
$ kubectl -n monitoring edit prometheuses/k8s

# Then delete the old stateful set
$ kubectl -n monitoring get statefulsets
NAME                READY   AGE
prometheus-k8s      1/1     6m12s
alertmanager-main   1/1     12d

$ kubectl -n monitoring delete statefulsets/prometheus-k8s
statefulset.apps "prometheus-k8s" deleted

# Then edit the prometheus operator to add the storage field and set paused: false
$ kubectl -n monitoring edit prometheuses/k8s

# Check logs to confirm that things 'worked'
$ kubectl -n monitoring logs -f prometheus-operator-5b7946f4d6-ctlsk --container prometheus-operator
level=info ts=2020-11-28T23:04:45.721632727Z caller=operator.go:427 component=alertmanageroperator msg="sync alertmanager" key=monitoring/main
```


At this point, feel free to `describe statefulsets prometheus-k8s` and check the `Volume Claims` field:

```bash
$ kubectl -n monitoring describe statefulsets prometheus-k8s
<...snip...>
Volume Claims:
  Name:          prometheus-k8s-db
  StorageClass:  MyCustomStorageClassHere
  Labels:        <none>
  Annotations:   <none>
  Capacity:      10Gi
  Access Modes:  [ReadWriteOnce]
```

I didn't find out about the `pause` until I saw errors like this in the operators logs:

```bash
$ kubectl -n monitoring logs -f prometheus-operator-5b7946f4d6-ctlsk --container prometheus-operator
<...Snip...>
level=info ts=2020-11-28T22:55:22.95538757Z caller=operator.go:1122 component=prometheusoperator msg="sync prometheus" key=monitoring/k8s
level=info ts=2020-11-28T22:55:23.130633559Z caller=operator.go:1187 component=prometheusoperator msg="resolving illegal update of Prometheus StatefulSet" details="&StatusDetails{Name:prometheus-k8s,Group:apps,Kind:StatefulSet,Causes:[]StatusCause{StatusCause{Type:FieldValueForbidden,Message:Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden,Field:spec,},},RetryAfterSeconds:0,UID:,}"
```

Which brought me to this thread:

https://github.com/prometheus-operator/prometheus-operator/issues/233#issuecomment-289382100


```
My suggestion number one is to have Persistent Volumes, that way even when there are disruptive changes like these at least the Prometheus data is kept through deployments. Then for an upgrade like this it is easiest to set the Paused field in the Prometheus resource to true, that way the Prometheus Operator does not reconcile the underlying StatefulSet anymore. Then the StatefulSet can be removed, and Paused can be set to false and the Prometheus Operator will recreate the StatefulSet correctly.

We're trying to finalize and minimize the breaking changes we're doing, but being an alpha stage project we explicitly declare that there may still be breaking changes in any release while in alpha.
```
