### ISSUE TITLE
documentation - NGINX Ingress is ambiguity

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#1863]
[addon-ingress](https://microk8s.io/docs/addon-ingress) 

> This addon adds an NGINX Ingress Controller

but multiple projects have identical/similar names. Very confusing to a novice.
[NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx)
[NGINX Ingress Controller](https://github.com/nginxinc/kubernetes-ingress)

Request 1: Would it be possible to add a link to the correct project on your page to remove this ambiguity?

Request 2:  Is microk8s is simply packaging one of the above or adding functionality or doing some special integration?  Whatever the answer, could a few sentences be added.  Depending on how similar/different, readers will get some insight as to how much they rely on documentation from the source.

[annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/) list all valid annotations.  But not sure if this is the correct project for microk8s?  

Request 3: Would it be possible to add a link to where all valid ConfigMaps and annotations are defined for the microk8s ingress addon?

[cert-manager tutorial](https://cert-manager.io/docs/tutorials/acme/http-validation/) makes reference to class nginx.

```
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
```

Request 4: Is microk8s ingress class named "nginx"? is microk8s ingress addon the same in cert-manager tutorial?  

When I add [kubernetes.io/ingress.class: "nginx"](https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/) to my ingress yaml it stops working.  So what is the correct class for microk8s ingress?

While the answer to the above may be obvious in someone skilled in the art of Kubernetes, it is not for this microk8s enthusiast.
