### ISSUE TITLE
Ingress - change default backend not working

### ISSUE THREAD

**Issue by Sekru** [ubuntu/microk8s#1891]
Hi, I trying to change default backend.
```
spec:
  defaultBackend:
    service:
      name: navigation-service
      port:
        number: 80
```
After apply I have got this
```
Name:             ingress-nginx
Namespace:        default
Address:          127.0.0.1
Default backend:  navigation-service:80 (10.1.173.59:80)

```
So I trying access my loclahost but still got 404. However if i curl 10.1.173.59 then I have got my static page exposed from pod.
I also added rule to check if i can get it from another path and it works.
```
          - pathType: Prefix
            path: /navigation(.*)
            backend:
              service:
                name: navigation-service
                port:
                  number: 80
```
So Why i still got 404 even if my service, and pod are correct? Ingress controller enabled from addons.

**Comment by ktsakalozos** [comment]
Hi @Sekru. I haven't don this before but don't you need to set a default back end annotation? [1]

[1] https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#default-backend

**Comment by Sekru** [comment]
> Hi @Sekru. I haven't don this before but don't you need to set a default back end annotation? [1]
> 
> [1] https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#default-backend

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/default-backend: navigation-service
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  defaultBackend:
    service:
      name: navigation-service
      port:
        number: 80
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /navigation(.*)
            backend:
              service:
                name: navigation-service
                port:
                  number: 80

          - pathType: Prefix
            path: /portainer(.*)
            backend:
              service:
                name: portainer-service
                port:
                  number: 9000
```
Still 404
