### ISSUE TITLE
microk8s ingress with custom ssl secret - appending an extra k8s namespace

### ISSUE THREAD

**Issue by AlbertoDePena** [ubuntu/microk8s#1920]
Please run `microk8s inspect` and attach the generated tarball to this issue.

```bash
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1856/inspection-report-20210120_164652.tar.gz
```

```bash
microk8s is running
high-availability: no
addons:
  enabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    ingress              # Ingress controller for external access
    metrics-server       # K8s Metrics Server for API access to service metrics
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    gpu                  # Automatic enablement of Nvidia CUDA
    ha-cluster           # Configure high availability on the current node
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    istio                # Core Istio service mesh services
    jaeger               # Kubernetes Jaeger operator with its simple config
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    multus               # Multus CNI enables attaching multiple network interfaces to pods
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
```

#### For some reason when the daemon tries to lookup the custom ssl secret, it appends an extra k8s namespace. Here is the error:

```W0120 16:29:44.275811       9 controller.go:1125] Error getting SSL certificate "namespace-dev/shared/wilcard-custom-tls": local SSL certificate namespace-dev/shared/wilcard-custom-tls was not found. Using default certificate```

`wilcard-custom-tls` is the secret and it is located in `shared` namespace. Not sure why its looking for `namespace-dev/shared/wilcard-custom-tls`

It should be looking in `shared/wilcard-custom-tls` not in `namespace-dev/shared/wilcard-custom-tls`

**Comment by balchua** [comment]
Hi @AlbertoDePena can you show the ingress controller definition?
If its even possible for you to upload the tarball generated by `inspect` command.

**Comment by AlbertoDePena** [comment]
I know it's not ingress definition related because it works in two different VMs but I can replicate the behaviour in two others.

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: my-ingress
  namespace: namespace-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
    - hosts:
        - <redacted>.com
      secretName: shared/wilcard-custom-tls
  rules:
    - host: <redacted>.com
      http:
        paths:
          - path: /some-path(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: some-service
              servicePort: 80
```
