### ISSUE TITLE
Running `kubectl rollout restart <mydeploy>` sometimes causes persistent volume to not work correctly

### ISSUE THREAD

**Issue by alexgleason** [ubuntu/microk8s#1998]
I have a Postgres database in a Pod with a persistent volume claim. Sometimes after restarts the database will be completely empty. If I restart it again, the database will be restored. This happens intermittently, every so often after a redeploy/restart.

I'm using `microk8s-hostpath` storage class, and I wonder if it has something to do with that. Why would a container run at all without its persistent volume? Could this be a deeper Kubernetes issue?

[inspection-report-20210209_235032.tar.gz](https://github.com/ubuntu/microk8s/files/5954938/inspection-report-20210209_235032.tar.gz)

EDIT: here's my full deployment script

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tribeshost
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: microk8s-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tribeshost-db
  namespace: tribeshost
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: microk8s-hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribeshost-deployment
  namespace: tribeshost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tribeshost
  template:
    metadata:
      labels:
        app: tribeshost
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: tribeshost-k8s-config
        secret:
          secretName: tribeshost-k8s-config
      - name: tribeshost-config
        secret:
          secretName: tribeshost-config
      - name: tribeshost-db
        persistentVolumeClaim:
          claimName: tribeshost-db
      containers:
      - image: tribeshost/tribeshost:latest
        imagePullPolicy: Always
        name: tribes
        ports:
        - containerPort: 4000
        env:
        - name: MIX_ENV
          value: prod
        volumeMounts:
        - name: tribeshost-k8s-config
          mountPath: /opt/app/.kube
          readOnly: true
        - name: tribeshost-config
          mountPath: /opt/app/config/runtime.exs
          subPath: runtime.exs
          readOnly: true
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: tribes
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: tribeshost-db
          mountPath: "/var/lib/postgresql/data"
---
apiVersion: v1
kind: Service
metadata:
  name: tribeshost-service
  namespace: tribeshost
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    port: 4000
  selector:
    app: tribeshost
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: tribeshost-httpproxy
  namespace: tribeshost
spec:
  virtualhost:
    fqdn: tribes.host
    tls:
      secretName: tribeshost-tls-secret
  routes:
    - conditions:
      - prefix: /
      enableWebsockets: true
      services:
        - name: tribeshost-service
          port: 4000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tribeshost-certificate
  namespace: tribeshost
spec:
  secretName: tribeshost-tls-secret
  dnsNames:
    - tribes.host
  issuerRef:
    name: tribes-letsencrypt
    kind: ClusterIssuer
```
