### ISSUE TITLE
ingress config http-snippet

### ISSUE THREAD

**Issue by virtyos** [ubuntu/microk8s#2036]
How can I add `proxy_cache_path ` to http section of ingress addon nginx config?

I'm trying to create a config map

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  http-snippet: "proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=mycache:32m use_temp_path=off max_size=4g inactive=24h;"
```

and apply it `microk8s kubectl apply -f  config.yaml`
but it's not working
the result of `microk8s kubectl exec nginx-ingress-microk8s-controller-4wsxk -n ingress -- cat /etc/nginx/nginx.conf` doesn't contain my proxy_cache_path

**Comment by balchua** [comment]
did you restart the nginx pods?  I dont know if the nginx pods can automatically update when configmap changes.

**Comment by virtyos** [comment]
> did you restart the nginx pods? I dont know if the nginx pods can automatically update when configmap changes.

No, I didn't. What to restart? Ingress controller pod? How to do it safely? But I never found any words about it's necessary  to restart controller pod.

**Comment by balchua** [comment]
Im not sure if the nginx ingress controller automatically reloads the configmap.
Since the nginx ingress controller is a daemonset and stateless i normally simply delete the pod one by one.

**Comment by virtyos** [comment]
Finally I found out: 
1) ingress controller automatically reloads the configmap 
2) we must use nginx-load-balancer-microk8s-conf

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
data:
  http-snippet: "proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=mycache:32m use_temp_path=off max_size=4g inactive=24h;"
```
