### ISSUE TITLE
Export of cluster configuration uses loopback 127.0.0.1 for server

### ISSUE THREAD

**Issue by mconner** [ubuntu/microk8s#2131]
I want to be able to run kubectl and helm from my Windows environment against clusters on a remote vm as well as locally installed under multipass.  To do this I need to export the config to a local file, and set my KUBECONFIG environment variable to that file.  This worked with minikube (at least locally).  However, when I export the config under microk8s, I get what you see below (though normally, I'd use --raw):
```
daruser@darqa:~$ sudo microk8s kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: REDACTED
```
The problem is that the server is given as localhost, which does no good if not local.  This happens both on vm in VSphere where the ip is static, and hosted on my dev machine, using multipass, where it is not.    I can't change the IP to a name, because then I get an error like:

```
$ kubectl get pods
Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, not darqa
```
So it seems its OK with IPs but if it gets a name, it is checking.

On the remote vm, where the IP is static, I can do some sed processing of the file to correct it, and I could probably do that with the multipass vm, as well, but I'd have to update it every time I restart, since the IP changes (unless I add my own static IPs).
However, this is a bit of a pain, **It would be helpful of there was some way to specify the interface that should be used when generating the config view**.

`microk8s inspect` generated tarball:
[inspection-report-20210325_134856.tar.gz](https://github.com/ubuntu/microk8s/files/6205095/inspection-report-20210325_134856.tar.gz)
