### ISSUE TITLE
Indentation error in yaml output of microk8s.status

### ISSUE THREAD

**Issue by krichter722** [ubuntu/microk8s#2147]
The output of `microk8s.status` is

```
microk8s:
  running: False
high-availability:
  enabled: False
   message: microk8s is not running. Use microk8s inspect for a deeper inspection.
```

which confuses some parsers (e.g. the built-in Python 3.8) due to the extraneous space before `message`.
