### ISSUE TITLE
mysql container created does not configure using the env values.

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#218]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20181129_181519.tar.gz](https://github.com/ubuntu/microk8s/files/2628620/inspection-report-20181129_181519.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
Found 2 bugs:
(1) The mysql root password is not set from my kubernetes secret. It is still using the "password" as it's root password.
(2) The database specified is not created at all.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "svc-db"
  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: app-db # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: app-db # Has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: Always
        env:
         - name: MYSQL_ROOT_USERNAME
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: username
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: password
         - name: MYSQL_DATABASE
           value: iconverse
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysqlinit 
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```
```
$ k exec -it mysql-0 -- bash
root@mysql-0:/# mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.13 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0.02 sec)

mysql> ^DBye
root@mysql-0:/# echo $MYSQL_DATABASE
iconverse
root@mysql-0:/# 
```
```
$ k get secret
NAME                                                TYPE                                  DATA   AGE
default-token-s6bpp                                 kubernetes.io/service-account-token   3      6d
istio.default                                       istio.io/key-and-cert                 3      5d21h
istio.nginx-ingress-microk8s-serviceaccount         istio.io/key-and-cert                 3      5d21h
mysql-secret                                        Opaque                                2      12m
nginx-ingress-microk8s-serviceaccount-token-v64vg   kubernetes.io/service-account-token   3      5d21h
$ k describe secret mysql-secret
Name:         mysql-secret
Namespace:    default
Labels:       <none>
Annotations:  
Type:         Opaque

Data
====
password:  20 bytes
username:  5 bytes
```
