### ISSUE TITLE
Ingress Objects does not report an IP over kubectl

### ISSUE THREAD

**Issue by sr229** [ubuntu/microk8s#222]
Somehow, Ingress objects does not have an IP.

I don't know this is intended behavior but in able for me to use the following exposed objects I need their IP the ingress object is exposed at.

```sh
enra@sakura:~$ kubectl get ingress
NAME                 HOSTS                      ADDRESS   PORTS     AGE
wanton-ostrich-api   api.local.containerum.io             80        14m
wanton-ostrich-ui    local.containerum.io                 80        14m
```

[inspection-report-20181201_071849.tar.gz](https://github.com/ubuntu/microk8s/files/2635677/inspection-report-20181201_071849.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @sr229,

Thank you for openeing this issue. Ingress is available on localhost port 80 so the address you are looking for is 127.0.0.1. Here is an example where we setup a microbot service and make it available via the ingress controller. Note that we set the host to be `microbot.127.0.0.1.xip.io` so that a dns lookup would return 127.0.0.1:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microbot
  name: microbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microbot
    spec:
      containers:
      - image: cdkbot/microbot-amd64
        imagePullPolicy: ""
        name: microbot
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 30
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: microbot
  labels:
    app: microbot
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: microbot
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: microbot-ingress
spec:
 rules:
   - host: microbot.127.0.0.1.xip.io
     http:
       paths:
         - path: /
           backend:
             serviceName: microbot
             servicePort: 80
```

You are right that the address reported by `microk8s.kubectl get ingress` is empty. In order to have ingress report `127.0.0.1` as the address you need to add `--publish-status-address=127.0.0.1` in the arguments of the `nginx-ingress-microk8s-controller`. Here is how to do that:

```
microk8s.kubectl edit  ds nginx-ingress-microk8s-controller
```

And then you update the args section to looks like this:
```
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
        - --publish-status-address=127.0.0.1

```

This is a temporary fix as we intend to update the ingress manifest appropriately.

Hope this helps and thank you for using microk8s.
