### ISSUE TITLE
FeatureRequest : there needs to be a way to add "feature-gates" to kubelet as like in Kind.

### ISSUE THREAD

**Issue by velcrine** [ubuntu/microk8s#2306]
using Kind, we can add a featuregate like this:
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EphemeralContainers=true"
```

Requesting for a similar feature
