### ISSUE TITLE
PVC Re-Size no suitable plugin error.

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [ubuntu/microk8s#2358]
Hey Canonical Team,

We have created a `STS` and are using `VolumeClaimTemplates` for PV and PVC. When we try to re-size the PVC, we get below error. 

```yaml
VolumeMode:    Filesystem
Used By:       es-cluster-2
Events:
  Type     Reason             Age                From           Message
  ----     ------             ----               ----           -------
  Warning  ExternalExpanding  3s (x2 over 111m)  volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

Below is our `StorageClass` file and `VolumeClaimTemplate` section of STS.

`VolumeClaimTemplate`
```yaml
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: elasticsearch
      spec:
        accessModes: ["ReadWriteOnce"]
        # volumeName: elasticsearch-volume
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 2Gi
```
`StorageClass`

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
  annotations:
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
```

Below is output of `describe storageclass` and `describe pvc`

```yaml
$ microk8s kubectl describe sc
Name:                  microk8s-hostpath
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           microk8s.io/hostpath
Parameters:            <none>
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>
```

```yaml
$ microk8s kubectl describe pvc data-es-cluster-2
Name:          data-es-cluster-2
Namespace:     default
StorageClass:  microk8s-hostpath
Status:        Bound
Volume:        pvc-4ad3bb54-8803-477b-9466-1b63626c7b59
Labels:        app=elasticsearch
Annotations:   control-plane.alpha.kubernetes.io/leader:
                 {"holderIdentity":"6da2da0c-d4c0-11eb-883b-2212e7c8603b","leaseDurationSeconds":15,"acquireTime":"2021-06-24T07:58:54Z","renewTime":"2021-...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       es-cluster-2
Events:
  Type     Reason             Age                   From           Message
  ----     ------             ----                  ----           -------
  Warning  ExternalExpanding  3m50s (x2 over 115m)  volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
```

Also attaching `Microk8s inspect` tarball output below. 

[inspection-report-20210624_103341.tar.gz](https://github.com/ubuntu/microk8s/files/6708468/inspection-report-20210624_103341.tar.gz)
