### ISSUE TITLE
question: Something about snapcraft or build

### ISSUE THREAD

**Issue by huang12zheng** [ubuntu/microk8s#2425]
1. Is it ok if I make a new package without etcd and etcdctl?
   In other word,Can I delete, locally, etcd that is parts of snapcraft.yaml
2. Could you please give me an example about Slots

```yaml
slots:
  microk8s:
    interface: content
    content: microk8s
    source:
      read: [$SNAP/.microk8s-info/microk8s]
```

3. Could you explain that cluster-agent in snapcraft.yaml?
    Whether it simply provides a stage-packages dependency
    and which is the same as bash-utils.stage-packages or microk8s.stage-packages
