### ISSUE TITLE
Loosing Entripoint objects

### ISSUE THREAD

**Issue by matlad** [ubuntu/microk8s#2432]
After restart of any node, I am missing  manually added endpoints.
(I'm using them for GlusterFS volume.)
glusterfs.yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs
  namespace: test
subsets:
- addresses:
  - ip: 10.10.0.01
  - ip: 10.10.0.02
  - ip: 10.10.0.03
  ports:
  - port: 1
    protocol: TCP
```
