### ISSUE TITLE
Ingress controller with custom bind-address (or custom port) doesn't work

### ISSUE THREAD

**Issue by typoworx-de** [ubuntu/microk8s#2546]
I'm new to microk8s using the snap setup on ubuntu. I need the ingress to run on custom IP address as port 80/443 is already in use on the development system.

At first I tried to override startup-arguments using ```/var/snap/microk8s/current/args/ingress```, but it appears that this is ignored.
The config yaml is read-only in path ```/snap/microk8s/current/microk8s-resources/actions/ingress.yaml```

So how can I make ingress listen on it's own IP like 127.1.1.1 or even an external IP address? I already searched through docs (https://microk8s.io/docs) but there was nothing helpful at all giving me any hint on this problem.

**Comment by typoworx-de** [comment]
Seems to be an issue not resolved perfectly:
#824  (workaround not working with snaps-setup and read-only files)
#1499 still recommending workaround (proposed as "fix") in #824

Why is there no "/var/snap/microk8s/current/args/ingress" being able to modify ingress startup arguments nor any way to patch/override ingress yaml configuration with custom IP?

**Comment by typoworx-de** [comment]
Tried to override enable.ingress.sh and ingress.yaml using this path:
```/var/snap/microk8s/current/microk8s-resources/actions/```

No luck they are ignored same as ```/var/snap/microk8s/current/args/ingress```

For my purpose this renders microk8s nearly useless and I was not able to fix the deploy or doing a manual deploy for ingress. Why the hell it is so hard to change the IP for ingress?!

**Comment by ktsakalozos** [comment]
Hi @typoworx-de 

At this point configuring the addon manifests (including ingress) is not supported. Here are a few ways you can customize your deployments:

- Make a copy of the ingress manifest, edit it, and kubeclt apply it. 
```
cp /snap/microk8s/current/actions/ingress.yaml .
# Edit the local copy of the ingress.yaml by replacing 
# $TAG with the ingress image tag (the addon script uses "v1.0.0-alpha.2")
# $DEFAULT_CERT with the default ssl certificate you may want, and 
# $EXTRA_ARGS with any extra arguments you want to pass to the ingress process in your case you can add "- --publish-status-address=127.1.1.1"
# Apply the patched manifest with
microk8s.kubectl apply -f ingress.yaml
```  

- Edit the ingress manifest after deployment. First enable the ingress addon and then `microk8s.kubectl edit` the part you want to change.
```
microk8s.kubectl enable ingress
microk8s.kubectl edit -n ingress       daemonset.apps/nginx-ingress-microk8s-controller
```

**Comment by typoworx-de** [comment]
> Hi @typoworx-de
>     * Make a copy of the ingress manifest, edit it, and kubeclt apply it.

Thanks for the hint. I'll try that. My first tries in this direction where not very successful yet.

**Comment by typoworx-de** [comment]
@ktsakalozos may be you have a tip for me.

For some reason even the original ingress.yaml fails after being copied:
```
# cp /snap/microk8s/current/actions/ingress.yaml /var/snap/microk8s/current/actions/ingress.yaml
# microk8s.kubectl apply -f /var/snap/microk8s/current/actions/ingress.yaml

namespace/ingress unchanged
serviceaccount/nginx-ingress-microk8s-serviceaccount unchanged
clusterrole.rbac.authorization.k8s.io/nginx-ingress-microk8s-clusterrole unchanged
role.rbac.authorization.k8s.io/nginx-ingress-microk8s-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s unchanged
rolebinding.rbac.authorization.k8s.io/nginx-ingress-microk8s unchanged
configmap/nginx-load-balancer-microk8s-conf unchanged
configmap/nginx-ingress-tcp-microk8s-conf unchanged
configmap/nginx-ingress-udp-microk8s-conf unchanged
error: error parsing /var/snap/microk8s/current/actions/ingress.yaml: error converting YAML to JSON: yaml: line 52: could not find expected ':'
```
Why? I'm trying to install snap version of microk8s with release 1.19 (which is pre-condition by one of my clients I'm working for now).

This is the ingress.yaml for the given version 1.19:
https://github.com/ubuntu/microk8s/blob/1.19/microk8s-resources/actions/ingress.yaml

I've downloaded it and diff doesn't show any file differences!

**Comment by typoworx-de** [comment]
Okay found the culprit. It looks like the variables filled used later in Bash-Script(?) are the problem:
https://github.com/ubuntu/microk8s/blob/1.19/microk8s-resources/actions/ingress.yaml#L186
```
$DEFAULT_CERT
 $EXTRA_ARGS
```

Removing them from original copy of ingress.yaml makes the 'kubectl apply' work. I'm testing now if I'll get the rest working. I need to remove $EXTRA_ARGS and replace it with ```- --publish-status-address=x.x.x.x``` (x.x.x.x = my custom IP).

**Comment by typoworx-de** [comment]
I'v tried to patch the ingress-config as proposed using:
```microk8s.kubectl edit -n ingress daemonset.apps/nginx-ingress-microk8s-controller```

and edited: spec.template.spec.args adding this line:
```
- --publish-status-address=127.107.56.115
```

This change works, but ingress still won't work throwing this errors:
```
Failed to apply default image tag "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:$TAG": couldn't parse image reference "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:$TAG": invalid reference format
```
Which seems to has to do with another variable $TAG in metadata.annotations.kubectl.kubernetes.io/last-applied-configuration.
```
pod: "nginx-ingress-microk8s-controller-whpsh_ingress(d0336ddd-eee4-4681-b81d-e1df154af726)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
```

Any tips how to resolve this the best way?

**Comment by ktsakalozos** [comment]
Try to

> # Edit the local copy of the ingress.yaml by replacing 
> # $TAG with the ingress image tag (the addon script uses "v1.0.0-alpha.2")

**Comment by typoworx-de** [comment]
Just for interest is it also possible using an ingress.yaml containing only patch above the existing one and being able to replace variables inside?

I've tried with this one working:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---  
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
  labels:
    microk8s-application: nginx-ingress-microk8s
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:$TAG
        name: nginx-ingress-microk8s
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-microk8s-conf
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-tcp-microk8s-conf
        - --udp-services-configmap=$(POD_NAMESPACE)/nginx-ingress-udp-microk8s-conf
        - ' '
        - --publish-status-address=127.107.56.115
```

Trying to apply it like this:
```
TAG=0.33.0 microk8s.kubectl apply -f /var/snap/microk8s/current/actions/ingress.patch.yaml
```
But found no way to make $TAG being replaced correctly (it's replaced with $TAG like in patch yaml above). Indeed it doesn't work by simply dropping the image-attribute, which  makes kubectl complain about that missing property.
