### ISSUE TITLE
How to 'microk8s enable gpu' in a mixed cluster?

### ISSUE THREAD

**Issue by copiltembel** [ubuntu/microk8s#2729]
I have a microk8s cluster in which the machines are mixed: some have GPUs and others don't. The master node does NOT. 

I am trying to enable GPU usage by running `microk8s enable gpu`. But I get this:

Nothing to do for `gpu`.

I've also tried removing the GPU nodes from the cluster, enabling microk8s gpu, then rejoining the cluster. Then tried to run nvidia/samples:vectoradd-cuda10.2 like this

```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test
spec:
  restartPolicy: OnFailure
  nodeSelector: 
    hasgpu: "true"
  containers:
  - name: cuda-vector-add
    image: "nvidia/samples:vectoradd-cuda10.2"
    resources:
      limits:
         nvidia.com/gpu: 1
```

But this led to the pod being stuck in `Pending` and with events saying that the pod cannot be scheduled.

`Warning   FailedScheduling          pod/gpu-operator-test   0/4 nodes are available: 4 Insufficient nvidia.com/gpu.`

Is there a possibility to enable the GPU even if not all the nodes in the cluster have a GPU?
