### ISSUE TITLE
NodePort restrictions?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#284]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
I want to expose my cluster in a single-node to  external access and use nodePort for that purpose. However, it restricts port range to start from 30000. Is there any good reason for that? How can I change that to default HTTP and HTTPS ports? Thanks!

**Comment by ktsakalozos** [comment]
Hi @khteh 

Have a look at https://kubernetes.io/docs/concepts/services-networking/service/#nodeport to see how to change the port range of NodePort. Also, be aware that at this point MicroK8s is not recommended for production environments. There are security concerns that you need to address yourself.

**Comment by khteh** [comment]
Hi @ktsakalozos, can you give more details about the security concern of using microk8s? Would using the mainstream kubectl address that concern? Thanks.

**Comment by khteh** [comment]
Hi @ktsakalozos, how to configure the --service-node-port-range in microk8s? I found the following configuration files but everytime when I `sudo vi` the file, it warns me of `Changing a readonly file`:
```$ find . -name "*kubelet*" -print
./build/kube_bins/v1.13.1/amd64/kubelet
./command-daemon-kubelet.wrapper
./configs/kubelet.config
./default-args/kubelet
./kubelet
./microk8s-resources/default-args/kubelet
./microk8s-resources/kubelet.config
```

**Comment by ktsakalozos** [comment]
@khteh, you will need to add the `--service-node-port-range` argument to ` /var/snap/microk8s/current/args/kube-apiserver` and then `sudo systemctl restart snap.microk8s.daemon-apiserver`.

In respect to security, I am not sure how and to whom MicroK8s will be exposed, but you should be aware that MicroK8s does not take any action to protect its endpoints (eg port 8080). Some of those security concerns will be addressed in the upcoming releases as they are addressed by https://github.com/ubuntu/microk8s/pull/88 . Have a look at the PR as it describes what ports are left open .

**Comment by khteh** [comment]
I change the port range to 80-443 and apply the following nginx.yml:
```
apiVersion: v1
kind: Service
metadata:
  name: svc-iconverse
  annotations:
    external-dns.alpha.kubernetes.io/hostname: iconverse-k8s.taiger.io
spec:
  selector:
    app: nginx-iconverse
    tier: iconverse
  ports:
  - name: http
    protocol: "TCP"
    port: 80
    nodePort: 80
  - name: https
    protocol: "TCP"
    port: 443 
    targetPort: 443 
  type: NodePort
```
and get the following error:
```
error: unable to recognize "nginx.yml": Get http://localhost:8080/api?timeout=32s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
