### ISSUE TITLE
microk8s hostpath provisioner ignores "reclaimPolicy: Retain" for dynamic volume provisioning

### ISSUE THREAD

**Issue by hatzlj** [ubuntu/microk8s#290]
I've defined a storage class in my microk8s cluster and set the `reclaimPolicy: Retain` property on it:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my.db-storage
  labels:
    ikosa.stage: dev
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
Defining a PersistentVolume using this class works as expected, as the volume automatically gets the `persistentVolumeReclaimPolicy: Retain` set.
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  labels:
    my.volume: test
    my.stage: dev
spec:
  storageClassName: my.db-storage
  capacity:
    storage: 15Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/test"
```
```
kubectl describe persistentvolumes test
Name:            test
Labels:          my.stage=dev
                 my.volume=test
Annotations:     kubectl.kubernetes.io/last-applied-configuration:
                   {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"my.stage":"dev","my.volume":"test"},"name":"tes...
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    my.db-storage
Status:          Available
Claim:           
Reclaim Policy:  Retain
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        15Mi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /home/data/test
    HostPathType:  
Events:            <none>
```

Altough, when defining a PersistentVolumeClaim using this class, the Persistent Volume created dynamically gets the default `persistentVolumeReclaimPolicy: Delete` set.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: my.db-storage
```
```
kubectl describe persistentvolumes pvc-e273048d-1ec9-11e9-bab6-08002761592a
Name:            pvc-e273048d-1ec9-11e9-bab6-08002761592a
Labels:          <none>
Annotations:     hostPathProvisionerIdentity: my-microk8s-host
                 pv.kubernetes.io/provisioned-by: microk8s.io/hostpath
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    my.db-storage
Status:          Bound
Claim:           default/my-service-claim-db-data
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        100Mi
Node Affinity:   <none>
Message:         
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /var/snap/microk8s/common/default-storage/default-my-service-claim-db-data-pvc-e273048d-1ec9-11e9-bab6-08002761592a
    HostPathType:  
Events:            <none>

```
I tried to look into https://hub.docker.com/r/cdkbot/hostpath-provisioner, but there is no source repo linked.
