### ISSUE TITLE
StatefulSet RollingUpdate and ReadinessProbe parameters not available?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#294]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
Surprised to find that these are not available. Is this about microk8s or StatefulSet in general? Thanks.
```
ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "failureThreshold" in io.k8s.api.core.v1.HTTPGetAction, 
ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "initialDelaySeconds" in io.k8s.api.core.v1.HTTPGetAction, 
ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "periodSeconds" in io.k8s.api.core.v1.HTTPGetAction, 
ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "successThreshold" in io.k8s.api.core.v1.HTTPGetAction, 
ValidationError(StatefulSet.spec.template.spec.containers[0].readinessProbe.httpGet): unknown field "timeoutSeconds" in io.k8s.api.core.v1.HTTPGetAction, 
ValidationError(StatefulSet.spec.updateStrategy.rollingUpdate): unknown field "maxSurge" in io.k8s.api.apps.v1.RollingUpdateStatefulSetStrategy, 
ValidationError(StatefulSet.spec.updateStrategy.rollingUpdate): unknown field "maxUnavailable" in io.k8s.api.apps.v1.RollingUpdateStatefulSetStrategy]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by ktsakalozos** [comment]
Hi @khteh 

Given that MicroK8s goes through the Kubernetes certification process on every release, I suspect there must be something wrong with the manifest you are using. Would you be able to share a minimal yaml that is failing?

Thanks

**Comment by khteh** [comment]
```
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: iconverse-admin
  labels: 
    app: iconverse-admin
spec:
  serviceName: "svc-iconverse-admin"
#  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 2 # Default is 1
  updateStrategy: 
    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 50%
#      maxSurge: 50%
  selector:
    matchLabels:
      app: iconverse-admin # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels: 
        app: iconverse-admin # Has to match .spec.selector.matchLabels
    spec:   
      terminationGracePeriodSeconds: 10
      containers:
      - name: iconverse-admin
        image: <acc>.dkr.ecr.ap-southeast-1.amazonaws.com/iconverse-admin:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_CONFIG_NAME
          value: "application.yml"
        - name: SPRING_CONFIG_LOCATION
          value: "/etc/application/config/application.yml"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: iconverse-mysql-secret
              key: mysql-root-password
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
#          hostPort: 8081
        - containerPort: 8443
          name: https
          protocol: TCP
#          hostPort: 8082
        readinessProbe:
          httpGet:
            path: /
            port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 1
#            timeoutSeconds: 1
#            successThreshold: 1
#            failureThreshold: 1
```
