### ISSUE TITLE
liveness and readiness probe do not honour the parameters

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#334]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
I have these params for the liveness and readiness probe:
```
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
```
However, `kubectl describe pod <mypod>` Events: shows that it fails on the FIRST probe failure and there is no retry at all!
