### ISSUE TITLE
API admin password empty on 1.14/beta

### ISSUE THREAD

**Issue by sfriedel** [ubuntu/microk8s#373]
I was checking out the `1.14/beta` channel (v1.14.0-beta.1 2019-03-01 (442)) when I noticed that the kube api admin password in the `client.config` and `basic_auth.csv` were empty. 

This happened on a fresh installation with `snap install --classic --channel 1.14/beta microk8s`.

/var/snap/microk8s/current/credentials/client.config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REMOVED
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
    password: 
```

/var/snap/microk8s/current/credentials/basic_auth.csv
```
,admin,admin,"system:masters"
```

I suppose this is not the intended behavior because the API is exposing the secure port on `0.0.0.0` and this would grant everyone access by just providing the `admin` user name.

[inspection-report-20190324_100002.tar.gz](https://github.com/ubuntu/microk8s/files/3000186/inspection-report-20190324_100002.tar.gz)
