### ISSUE TITLE
Why does ingress redirect http to https?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#388]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

I just want http but it redirects to https. Any idea why?

My ingress.yml:
```
apiVersion: extensions/v1beta1
kind: Ingress 
metadata:
  name: ingress 
  namespace: default 
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "ingress-cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route" 
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
#    certmanager.k8s.io/issuer: "iconverse-letsencrypt"
#    certmanager.k8s.io/acme-challenge-type: http01
#    kubernetes.io/tls-acme: 'true'
  labels: 
    app: ingress 
spec:
  rules:  
    - host: 
      http:   
        paths:
          - path: /restapi
            backend:
              serviceName: svc-restapi
              servicePort: 8080
          - path: //restapi
            backend:
              serviceName: svc-restapi
              servicePort: 8080
          - path: /restapi/*
            backend:
              serviceName: svc-restapi
              servicePort: 8080
```
```
$ curl -Lv http://localhost:80/restapi/greeting
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /restapi/greeting HTTP/1.1
> Host: localhost
> User-Agent: curl/7.61.0
> Accept: */*
> 
< HTTP/1.1 308 Permanent Redirect
< Server: nginx/1.15.8
< Date: Wed, 27 Mar 2019 07:24:11 GMT
< Content-Type: text/html
< Content-Length: 171
< Connection: keep-alive
< Location: https://localhost/restapi/greeting
< 
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'https://localhost/restapi/greeting'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 1
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by termie** [comment]
I'm having this issues despite adding to the nginx-load-balancer-microk8s-conf configmap:
```
  data:
    ssl-redirect: "false"
```
and explicitly
```
apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: style
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
```

**Comment by termie** [comment]
it's using a fairly old version of ingress (0.15.), but even there the config key seems to exist https://github.com/kubernetes/ingress-nginx/blob/nginx-0.15.0/docs/user-guide/nginx-configuration/configmap.md

**Comment by khteh** [comment]
It works for me by adding the ` nginx.ingress.kubernetes.io/ssl-redirect: "false"` annotation. I am using `v1.14.0` and the ingress controller is `0.22.0`

**Comment by SamyCoenen** [comment]
The above annotation didn't work for me, but adding .local in the host field did solve the issue.
for example 
```
  spec:
    rules:
    - host: jenkins.local
      http:
        paths:
        - backend:
            serviceName: jenkins
            servicePort: 8080
          path: /
```
