### ISSUE TITLE
Trust insecure-registry "registry.container-registry" by default

### ISSUE THREAD

**Issue by robinchm** [ubuntu/microk8s#390]
Currently to pull images from the bundled private registry one needs to use the address "localhost:32000".

When DNS is also enabled, the private registry service is assigned a DNS record "registry.container-registry". From any pod on the cluster, `curl registry.container-registry:5000/v2/` returns expected result. But using this address for pulling images in the pod creation will fail:
```
  Warning  Failed     2m7s (x4 over 3m36s)  kubelet, xxx-xxxxxxx  Failed to pull image "registry.container-registry:5000/box": rpc error: code = Unknown desc = failed to resolve image "registry.container-registry:5000/box:latest": no available registry endpoint: failed to do request: Head https://registry.container-registry:5000/v2/box/manifests/latest: dial tcp: lookup registry.container-registry: no such host
```
From what I understand it tries to pull via https because this address is not added to insecure-registries when docker spins up. "localhost:32000" works because that address is added to the docker config.

Given that both DNS and registry are bundled DNS, can "registry.container-registry" be added to docker config so that we can use it in pods' yaml?

**Comment by ktsakalozos** [comment]
Hi @robinchm 

Can you please try this, edit `/var/snap/microk8s/current/args/containerd-template.toml` and right under the  `localhost:32000` entry add (not sure about the https vs http):
```
      [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://registry.container-registry:5000"]
```

Then do a `microk8s.stop` and after a few seconds a `microk8s.start`.

If that works we could put it in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/containerd-template.toml#L52 so that it is there by default.

**Comment by carlososiel** [comment]
Hi @ktsakalozos 
I have the same issue, and I tried with these configuration, but still try to pull from https instead of http.

**Comment by ktsakalozos** [comment]
@carlososiel can you please provide me with a way to reproduce the error you see? This "pull from https instead of http" sounds like a docker daemon needs to be configured to use the insecure registry MicroK8s provides. Please have a look at the comment https://github.com/ubuntu/microk8s/issues/382#issuecomment-477174066  where we have to tell the local dockerd that there is an insecure registry it can push images to.

**Comment by carlososiel** [comment]
@ktsakalozos I have installed version 1.14 of microk8s, with docker installed in version 18.09.3. The docker daemon has configurations for use insecure registry and with docker info show this information: 
```
Insecure Registries:
 192.168.100.114:32000
 127.0.0.0/8
```
And when I try to pull and image from these registry work fine:
```
docker pull 192.168.100.114:32000/test/api-proxy:240
240: Pulling from test/api-proxy
8e402f1a9c57: Already exists 
7b69d8b552de: Already exists 
42e747db7e28: Already exists 
4f8106e1c445: Already exists 
f57d5b707f97: Pull complete 
19d04a24e235: Pull complete 
ffa026816182: Pull complete 
Digest: sha256:1ae6ce5cdf7534a05220b961e6998faaa9b1fcbeb731c9f7b0e4d6879674ef04
```
But the version 1.14 of microk8s replace docker with containerd, and I configure cri plugin to use the same insecure registry, but not work, the pull always try to be from https instead of http

**Comment by ktsakalozos** [comment]
@carlososiel your docker on your host seems correctly configured then. Can you share the `/var/snap/microk8s/current/args/containerd-template.toml`? This is where you should add the insecure registries you have. (Make sure you do not mix tabs with spaces they are hard to find).

**Comment by carlososiel** [comment]
@ktsakalozos This is the registry config from my `containerd-template.toml`. 
```
[plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://192.168.100.114:32000"]
```

**Comment by robinchm** [comment]
I am not very familiar with containerd. Previously I could use `microk8s.docker ps` to retrieve what containers are currently being run. With `sudo microk8.sctr c ls` I get empty results while I do have a few pods running in the cluster. I thought containerd was managing all containers of microk8s?

**Comment by ktsakalozos** [comment]
@robinchm would these be of any good to you: `microk8s.ctr -n k8s.io images  ls` and `microk8s.ctr -n k8s.io c  ls`. Kubernetes is using the k8s.io namespaces.

@robinchm can you share the yaml you apply and you get this error? I need to test it.

**Comment by ktsakalozos** [comment]
@carlososiel can you show me how the registry at `http://192.168.100.114:32000` was setup? I also need to reproduce this to see what is failing.

**Comment by robinchm** [comment]
@ktsakalozos
The containerd command works! Thanks a lot.

The yaml I used for my pod is minimal:
```
apiVersion: v1
kind: Pod
metadata:
  name: box
  namespace: default
  labels:
    app: box
spec:
  containers:
  - name: box
    #image: localhost:32000/box
    image: registry.container-registry:5000/box
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
To reproduce this you need to push some long-running image to `localhost:32000/box` first (what I use is a ubuntu base image with some command to keep it alive, but I think any image would do). Then create a pod with the above yaml. Notice there is a line `image: localhost:32000/box` commented out, if I use that line instead the pod can spin up without problem.

**Comment by robinchm** [comment]
Maybe the containerd does not attempt to resolve against cluster DNS? It always uses host's network interface directly? Just guessing.

**Comment by cnhome** [comment]
@robinchm 你的配置文件不正确，你调整成下边的配置文件就可以了

```
[plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://registry.container-registry:5000"]
```

yaml文件这样设置就可以了

```
apiVersion: v1
kind: Pod
metadata:
  name: box
  namespace: default
  labels:
    app: box
spec:
  containers:
  - name: box
    image: local.insecure-registry.io/box
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

**Comment by cnhome** [comment]
@robinchm 你的配置文件是有问题的，请按照如下的步骤检查你的配置文件：

1. 检查配置文件/var/snap/microk8s/current/args/containerd-template.toml
```
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://192.168.0.102:5000"]
```
记得需要重新启动microk8s
```
sudo snap restart microk8s
```
2. 检查kubernetes的部署文件yaml关于image的配置
```
      containers:
      - name: mon-app
        image: local.insecure-registry.io/mon
```
注意：不需要配置端口

**Comment by robinchm** [comment]
@cnhome 
What I wanted was to use host name in pulling images, rather than using the default IP.
What you suggested would not work in this respect, and it even hard coded an IP that may change.

**Comment by amouat** [comment]
I note a lot of people in this thread are using the *1.3* containerd syntax for specifying registries, which isn't supported in containerd 1.2.5 that is currently shipped with microk8s https://github.com/ubuntu/microk8s/issues/702 
https://github.com/containerd/cri/issues/1143
https://github.com/containerd/containerd/releases/tag/v1.3.0

**Comment by SamyCoenen** [comment]
@robinchm why was this closed?
It's still not configured automatically when enabling the registry add-on

this is what I put:

```toml
[plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]
        [plugins.cri.registry.mirrors."registry.container-registry.svc.cluster.local:5000"]
          endpoint = ["http://registry.container-registry.svc.cluster.local:5000"]
```
Then afterwards do
`microk8s.stop`
`microk8s.start`
