### ISSUE TITLE
Cannot connect to microk8s from another machine

### ISSUE THREAD

**Issue by soapergem** [ubuntu/microk8s#421]
I just ran a fresh install of microk8s with this command:

```
sudo snap install microk8s --classic --channel=1.14/stable
```

I can access everything while I'm SSH'ed into the box this is running on, with commands much like this:

```
microk8s.kubectl get pods
```

However when I set my `~/.kube/config` file - on another machine on the same network - to this:

```
apiVersion: v1
clusters:
- cluster:
    server: http://192.168.1.123:8080
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
```

And then try to run this command:

```
kubectl get pods
```

I get this error message:

```
The connection to the server 192.168.1.123:8080 was refused - did you specify the right host or port?
```

In fact, when I run `curl localhost:8080` while on the box, I see valid K8S output, but if I try running `curl 192.168.1.123:8080` from outside the box, even that returns:

```
curl: (7) Failed to connect to 192.168.1.123 port 8080: Connection refused
```

I've tried a couple of things to get this working, first of which was allowing access to 8080 on the firewall with this command:

```
sudo ufw allow 8080
sudo ufw enable
```

Unfortunately that doesn't solve the problem. When I run `netstat -an | grep "LISTEN "` I can see an entry for port 8080 as follows:

```
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN
```

But because it says `127.0.0.1` instead of `0.0.0.0`, this would explain why it's not working off the box. Is there some `microk8s.*` command I don't know about, to open up access?
