### ISSUE TITLE
docs: upgrade documentation should highlight calico isn't upgraded as part of an upgrade

### ISSUE THREAD

**Issue by jack1902** [ubuntu/microk8s#4213]
#### Summary
The upgrade documentation here: https://microk8s.io/docs/upgrading highlights that `addons` are not upgraded by performing a microk8s upgrade which is understandable and is highlighted in those docs. However, `calico` isn't an addon and is something that is "baked in" to microk8s but isn't actually upgraded when performing an upgrade. I understand the reasoning behind this however i feel it should be called out in the documentation, as currently the only place i can find this information is in previously github issues.

relates to: https://github.com/canonical/microk8s/issues/3170

#### What Should Happen Instead?
Documentation should call out the fact that the CNI (Calico) isn't upgraded automatically as part of an upgrade and requires manual user intervention.

Simply adding a `note` would be helpful around where the updated calico manifest is, for clarity it is available here: `/snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml`

Below is an example snippet of ansible i use which ensures that `calico` is upgraded on a single host within the cluster.

ansible bits relates to: https://github.com/canonical/microk8s/issues/3880 and ability to check addons would be great: https://github.com/canonical/microk8s/issues/4130
```yaml
- name: Calico
  when: inventory_hostname == designated_host
  become: true
  block:
    - name: Copy new calico cni.yaml over original, creating a backup if there is a difference
      ansible.builtin.copy:
        src: /snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml
        dest: /var/snap/microk8s/current/args/cni-network/cni.yaml
        owner: root
        group: microk8s
        mode: '0660'
        backup: true
        remote_src: true
      register: calico

    - name: Apply updated cni.yaml
      ansible.builtin.command: "microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml"
      # Only apply if it there is a change
      when: calico.changed
      changed_when: true
```

#### Can you suggest a fix?
Document that `calico` isn't automatically upgraded when performing a microk8s upgrade
