### ISSUE TITLE
microk8s.enable ingress does not work when context namespace is not default

### ISSUE THREAD

**Issue by asfernandes** [ubuntu/microk8s#499]
When I set my context namespace to a custom one and use `microk8s.enable ingress`, the ingress controller objects are created on my namespace.

But when that happens it does not work when I create my ingress. Instead of display `127.0.0.1` in the address field of `kubectl get ingress`, it shows blank and the address is not accessible.

**Comment by balchua** [comment]
Oh yes. The service account `nginx-ingress-microk8s-serviceaccount` in the `clusterrolebinding` is bound to `default` namespace.  You can try the crb manifest below.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-microk8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-ingress-microk8s-clusterrole
subjects:
- kind: ServiceAccount
  name: nginx-ingress-microk8s-serviceaccount
  namespace: [your custom namespace]
```
