### ISSUE TITLE
[Question] Does microk8s support sgx?

### ISSUE THREAD

**Issue by HillLiu** [ubuntu/microk8s#546]
I have a docker image which support sgx ,  
It work fine with docker-compose, but not microk8s.

Is it mean microk8s not support sgx?

**Comment by ktsakalozos** [comment]
Hi @HillLiu , could you try MicroK8s from the edge channel (`sudo snap install microk8s --edge`) and attach here the tarball produced by `microk8s.inspect`. There were a few apparmor fixes recently.

**Comment by HillLiu** [comment]
Hi @ktsakalozos :

I face some issue.
after run sudo snap install microk8s --edge --classic

should I install something else?

```
Can't open /home/allentest/openssl-1.1.1c/lib/ssl/openssl.cnf for reading, No such file or directory
140213754184768:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:72:fopen('/home/allentest/openssl-1.1.1c/lib/ssl/openssl.cnf','r')
140213754184768:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:79:
unable to find 'distinguished_name' in config
problems making Certificate Request
140213754184768:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto/conf/conf_lib.c:270:
-----)
```

**Comment by ktsakalozos** [comment]
What distribution are you on? openssl comes as a dependency to snapd, so I am  not sure why you get this error.

**Comment by HillLiu** [comment]
After install sgx device plugin, 
sudo snap alias microk8s.kubectl kubectl

Try --edge and without --edge both work now.

**Comment by ktsakalozos** [comment]
Do you think we should have a `microk8s.enable sgx` add-on? The sgx-device-plugin does not seem to be under heavy development. Creating the add-on could be as simple as placing the daemonset yaml under https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions

**Comment by HillLiu** [comment]
@ktsakalozos I'm not familiar with microk8s add-on.

But I could share my daemonset.yaml.

```
apiVersion: apps/v1
kind: DaemonSet 
metadata:
  name: sgx-device-plugin 
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sgx-device-plugin
  template:
    metadata:
      labels:
        app: sgx-device-plugin
    spec:
      containers:
        - name: sgx-device-plugin
          image: sebvaucher/sgx-deviceplugin:0.1 
          imagePullPolicy: IfNotPresent 
          volumeMounts:
            - name: dev-isgx
              mountPath: /dev/isgx
            - name: dev-mei0
              mountPath: /dev/mei0 
            - name: aesm-socket 
              mountPath: /var/run/aesmd
            - name: kubeletsockets
              mountPath: /var/lib/kubelet/device-plugins 
      volumes:
        - name: dev-isgx
          hostPath:
            path: /dev/isgx
        - name: dev-mei0 
          hostPath:
            path: /dev/mei0
        - name: aesm-socket
          hostPath:
            path: /var/run/aesmd
        - name: kubeletsockets 
          hostPath:
            path: /var/lib/kubelet/device-plugins

```
