### ISSUE TITLE
kube-proxy exposes service only on tcp6

### ISSUE THREAD

**Issue by aldib** [ubuntu/microk8s#611]
1. Install microk8s on Ubuntu 18.4 using `snap install microk8s --classic --channel 1.13/stable`.
2. Create deployment and service for PostgreSQL using:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: graphql
  labels:
    name: graphql

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: graphql
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: graphql
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # type: LoadBalancer
  type: NodePort
  selector:
    app: postgres
```
 3. `microk8s.kubectl --namespace=graphql get service postgres` shows that the deployment was successful and that the service is available on  port 30589:
```
NAME       TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
postgres   NodePort   10.152.183.95   <none>        5432:30589/TCP   9m38s
```
4. However, `sudo netstat -tulpan |grep LISTEN |grep kube` shows that the service is only bound to ipv6 and not ipv4 so I can't connect to it using the PostgreSQL client:
```
tcp        0      0 127.0.0.1:42267         0.0.0.0:*               LISTEN      11475/kubelet
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      11475/kubelet
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      11450/kube-proxy
tcp6       0      0 :::10250                :::*                    LISTEN      11475/kubelet
tcp6       0      0 :::6443                 :::*                    LISTEN      11406/kube-apiserve
tcp6       0      0 :::10251                :::*                    LISTEN      11464/kube-schedule
tcp6       0      0 :::10252                :::*                    LISTEN      11535/kube-controll
tcp6       0      0 :::10255                :::*                    LISTEN      11475/kubelet
tcp6       0      0 :::8080                 :::*                    LISTEN      11406/kube-apiserve
tcp6       0      0 :::10256                :::*                    LISTEN      11450/kube-proxy
tcp6       0      0 :::10257                :::*                    LISTEN      11535/kube-controll
tcp6       0      0 :::10259                :::*                    LISTEN      11464/kube-schedule
tcp6       0      0 :::35607                :::*                    LISTEN      11450/kube-proxy
tcp6       0      0 :::30589                :::*                    LISTEN      11450/kube-proxy
tcp6       0      0 :::35101                :::*                    LISTEN      11450/kube-proxy
```

The tarball generated with `microk8s.inspect` is attached.

Any help would be appreciated.

Thank you
[inspection-report-20190823_100818.tar.gz](https://github.com/ubuntu/microk8s/files/3533794/inspection-report-20190823_100818.tar.gz)
