### ISSUE TITLE
Path is not honored in Local Persistent Volumes

### ISSUE THREAD

**Issue by v-garcia** [ubuntu/microk8s#613]
I created a [Local Volume](https://kubernetes.io/docs/concepts/storage/volumes/#local) linked by a PersistentVolumeClaim witch is used in a statefull set.
But whatever the ``local.path`` attribute I choose for my volume, it's always created in ``/var/snap/microk8s/common/default-storage/default-myname-pvc-34....``.

Is it the normal behavior or did I miss something ? Thanks a lot for your help.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myname
  labels:
    type: local
spec:
  capacity:
    storage: 400Gi
  accessModes:
    # the volume can be mounted as read-write by many nodes
    - ReadWriteMany
    # Allow WaitForFirstConsumer
  storageClassName: local-storage
  local:
    path: /data/download
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - main-pc
```
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myname
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
```
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
