### ISSUE TITLE
Failed cloning to gitRepo Volume

### ISSUE THREAD

**Issue by xrogtolis** [ubuntu/microk8s#680]
Creating the following volume in a Pod:
```
...
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/luksa/kubia-website-example.git
      revision: master
      directory: .
```
fails with the following message from the Pod description:
```
...
Events:
  Type     Reason       Age                From                             Message
  ----     ------       ----               ----                             -------
  Normal   Scheduled    <unknown>          default-scheduler                Successfully assigned default/gitrepo-volume-pod to ubuntu-16gb-nbg1-dc3-5
  Warning  FailedMount  20s (x7 over 52s)  kubelet, ubuntu-16gb-nbg1-dc3-5  MountVolume.SetUp failed for volume "html" : failed to exec 'git clone -- https://github.com/luksa/kubia-website-example.git .': Cloning into '.'...
/usr/lib/git-core/git-remote-https: relocation error: /lib/x86_64-linux-gnu/libnss_dns.so.2: symbol __res_context_search version GLIBC_PRIVATE not defined in file libresolv.so.2 with link time reference
: exit status 128
```
[inspection-report-20190926_163445.tar.gz](https://github.com/ubuntu/microk8s/files/3658298/inspection-report-20190926_163445.tar.gz)
