### ISSUE TITLE
Error in events

### ISSUE THREAD

**Issue by heckad** [ubuntu/microk8s#830]
Recently all containers in microk8s cluster were restarted. In events I found 
```
(combined from similar events): Readiness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "b5b7ad431e1d9c795f6922bd688d8593b9ad81b8ebb765f5707f94616502f253": OCI runtime exec failed: fork/exec /snap/microk8s/1073/bin/runc: too many open files: unknown
```
What does it mean?

**Comment by balchua** [comment]
My guess is that some pods are opening sockets, files etc that are not propert closed.  Check the code behind what the livenessProbe or readinessProbe is doing.

You can always increase the linux ulimit to alleviate this.

**Comment by heckad** [comment]
> You can always increase the linux ulimit to alleviate this.

How to do it for the container? 

Thanks for helping

**Comment by balchua** [comment]
The number you gave is already high.  Where is this set?

Last time i did this was when im installing elasticsearch on k8s.

The yaml came with an init container.

```
      initContainers:
      - name: set-vm-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
```
