### ISSUE TITLE
Improve the microk8s.status command

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#900]
We would like to improve the `microk8s.status` command by offering descriptions for each addon.
This comes as a follow up to the work in https://github.com/ubuntu/microk8s/pull/876 and in an effort to address issues such as https://github.com/ubuntu/microk8s/issues/869. Please review the following doc [1] and leave comments as you see fit. Thanks.

[1] Improve microk8s.status proposal. https://docs.google.com/document/d/12Xi3CQvLwRyIvnUOnJLC2m521quDR4Akd7ytVX0kobA/edit?usp=sharing

**Comment by balchua** [comment]
Proposal sounds good.  I do like think of adding something like this `microk8s.status <addon name>` which can return `enabled` or `disabled`.  Each addon should have some sort of guard at the beginning to check whether it is already enabled or disabled.  This is to prevent certain addons restarting cluster components like apiserver.
It can prevent future addons might clash with other addons.  Wdyt?

**Comment by balchua** [comment]
Can we also keep the grouping of enabled/disabled addons even on yaml outputs?  Thinking more about this, do we still like to maintain 2 types of output?
Yaml looks readable.

**Comment by ktsakalozos** [comment]
> This is to prevent certain addons restarting cluster components like apiserver and prevent future addons clashing with other addons.

Can you give me an example? I am ok with the status query on an addon. Not sure I get the use case you describe.


> Yaml looks readable.

It looks readable now but not sure if it going to stay like this in the future. I would rather disconnect the human readable output and the machine readable one.

**Comment by balchua** [comment]
"clash with other addons".  Im thinking if lets say there are new addons in the future that cannot work with addons side by side with another addon.  As an addon developer, i would like to check if conflicting addon is enabled, i will print out an error when enabling it...  Saying "Addon 'X' is enabled... please disable the addon 'X' first. "
Regarding yaml, yes you're right.

**Comment by balchua** [comment]
@ktsakalozos i have updated the PR #876 to accomodate the changes.

Currently this is how it looks like in the console:

```
microk8s.status
microk8s is running
addons:
enabled:
  dns                  # CoreDNS is a DNS server/forwarder, written in Go, that chains plugins.
  helm3                # Helm 3: The package manager for Kubernetes
  rbac                 # Kubernetes Role Based Access Control

disabled:
  cilium               # Cilium CNI - https://cilium.readthedocs.io/en/stable/intro/
  dashboard            # Dashboard is a web-based Kubernetes user interface.
  fluentd              # Log forwarder Fluentd with Elasticsearch
  gpu                  # NVIDIA GPU support
  helm                 # Helm 2: The package manager for Kubernetes
  ingress              # NGINX Ingress Controller for Kubernetes
  istio                # Service mesh that provides traffic management, policy enforcement, and telemetry collection.
  jaeger               # Jaeger Operator
  juju                 # Juju is an open source application modeling tool developed by Canonical Ltd.
  knative              # Knative offers scale-to-zero, autoscaling, in-cluster builds, and eventing framework on Kubernetes.
  kubeflow             # The Kubeflow project is dedicated to making deployments of machine learning (ML) workflows on Kubernetes
  linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks.
  metallb              # MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
  metrics-server       # Metrics Server is a cluster-wide aggregator of resource usage data.
  prometheus           # Prometheus Operator -  https://github.com/coreos/prometheus-operator.git
  registry             # An implementation of the Docker Registry HTTP API V2 for use with docker 1.6+. - https://hub.docker.com/r/cdkbot/registry-amd64
  storage              # Hostpath provisioner CSI. - https://hub.docker.com/r/cdkbot/hostpath-provisioner-amd64
```
while the yaml output look like this:

```
microk8s.status -o yaml
microk8s:
   running: True
addons:
    enabled:
     - name: dns
       description: CoreDNS is a DNS server/forwarder, written in Go, that chains plugins.
       version: 1.6.6
     - name: rbac
       description: Kubernetes Role Based Access Control
       version:  
    disabled:
     - name: cilium
       description: Cilium CNI - https://cilium.readthedocs.io/en/stable/intro/
       version: 1.6
     - name: dashboard
       description: Dashboard is a web-based Kubernetes user interface.
       version: 2.0.0-beta5
     - name: fluentd
       description: Log forwarder Fluentd with Elasticsearch
       version:  
     - name: gpu
       description: NVIDIA GPU support
       version: 1.11
. . .
```

Checkout the screen capture here. 
[https://asciinema.org/a/qiDb5r5qUVSDBDBQwgLuPIDYn](microk8s.status)
