### ISSUE TITLE
[dashboard] should be exposed via ingress

### ISSUE THREAD

**Issue by grebennikov** [ubuntu/microk8s#906]
When running microk8s on the server, rather than doing port forwarding it should be possible to access the dashboard via ingress (similar to kubeflow dashboard)

**Comment by ktsakalozos** [comment]
Thank you for this request, it is brought up frequently. We need to address the need for easy access to the dashboard in a secure way. Until we do so, to access the dashboard have a look at the MicroK8s docs [1] and the dashboard upstream wiki [2]

[1] https://microk8s.io/docs/addon-dashboard
[2] https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md

**Comment by cedricdv** [comment]
So it's 2020 and this still hasn't been solved yet? Great go Kubernetes...

**Comment by tanzerm** [comment]
Enable the ingress addon:
`microk8s enable ingress`

and create an ingress ressource:
`
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: dashboard
  namespace: kube-system
spec:
  rules:
  - http:
      paths:
      - path: "/dashboard/?(.*)"
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
`

Now you can access the dashboard with `http://<Microk8s-IP>/dashboard/`

**Comment by ishuah** [comment]
> Enable the ingress addon:
> `microk8s enable ingress`
> 
> and create an ingress ressource:
> 
> ```
> ---
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   annotations:
>     kubernetes.io/ingress.class: nginx
>     nginx.ingress.kubernetes.io/rewrite-target: /$1
>     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
>   name: dashboard
>   namespace: kube-system
> spec:
>   rules:
>   - http:
>       paths:
>       - path: "/dashboard/?(.*)"
>         pathType: Prefix
>         backend:
>           service:
>             name: kubernetes-dashboard
>             port:
>               number: 443
> ```
> 
> Now you can access the dashboard with `http://<Microk8s-IP>/dashboard/`

Following these instructions I can access http://<Microk8s-IP>/dashboard/ but the page doesn't load correctly because the assets (styling, js, images) cannot be resolved correctly (404).

![Screenshot from 2020-12-07 20-38-37](https://user-images.githubusercontent.com/321040/101385128-6988f800-38cc-11eb-895b-f76df6182567.png)

Manually appending `/dashboard/` to the asset path fixes this issue. Any workaround?

**Comment by Rom888** [comment]
This works for me (microk8s 1.19):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: kube-system
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ redirect;
spec:
  # https://kubernetes.io/docs/concepts/services-networking/ingress/
  # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
  rules:
  - http:
      paths:
      - path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
```

**Comment by wuzhuoqing** [comment]
Thanks Rom888, works for me too. Other than in my microk8s I need to use Ingress class: public
```
I1225 18:15:43.940765       6 flags.go:205] Watching for Ingress class: public
W1225 18:15:43.940833       6 flags.go:208] Only Ingresses with class "public" will be processed by this Ingress controller
```

**Comment by Rom888** [comment]
Stop working after upgrading to 1.20
Empty ADDRESS:
```
kubectl get ing -n kube-system
NAME        CLASS    HOSTS   ADDRESS   PORTS   AGE
dashboard   <none>   *                 80      27m
```
@wuzhuoqing where should it be specified: "Ingress class: public"?

**Comment by jdallen-a10** [comment]
This isn't working in my 1.20.2 version:

```
root@mkube1:~# cat ingress-dashboard.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ redirect;
spec:
  # https://kubernetes.io/docs/concepts/services-networking/ingress/
  # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
  rules:
  - http:
      paths:
      - path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443

root@mkube1:~# microk8s kubectl apply -f ingress-dashboard.yaml
ingress.networking.k8s.io/dashboard created
root@mkube1:~# microk8s kubectl get ing -A
NAMESPACE     NAME        CLASS    HOSTS   ADDRESS   PORTS   AGE
kube-system   dashboard   <none>   *                 80      11s

```

Last lines of the ingress container logs:
```
I0225 21:04:04.660923       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583555", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress kube-system/dashboard
I0225 21:04:04.661260       6 controller.go:141] Configuration changes detected, backend reload required.
I0225 21:04:04.745626       6 controller.go:157] Backend successfully reloaded.
I0225 21:04:28.628083       6 status.go:275] updating Ingress kube-system/dashboard status from [] to [{127.0.0.1 }]
I0225 21:04:28.641134       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583595", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/dashboard
```

What am I doing wrong here?

**Comment by sellers** [comment]
> This isn't working in my 1.20.2 version:
> 
> ```
> root@mkube1:~# cat ingress-dashboard.yaml
> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: dashboard
>   namespace: ingress
>   annotations:
>     # use the shared ingress-nginx
>     kubernetes.io/ingress.class: public
>     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
>     nginx.ingress.kubernetes.io/rewrite-target: /$2
>     nginx.ingress.kubernetes.io/configuration-snippet: |
>       rewrite ^(/dashboard)$ $1/ redirect;
> spec:
>   # https://kubernetes.io/docs/concepts/services-networking/ingress/
>   # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
>   rules:
>   - http:
>       paths:
>       - path: /dashboard(/|$)(.*)
>         pathType: ImplementationSpecific
>         backend:
>           service:
>             name: kubernetes-dashboard
>             port:
>               number: 443
> 
> root@mkube1:~# microk8s kubectl apply -f ingress-dashboard.yaml
> ingress.networking.k8s.io/dashboard created
> root@mkube1:~# microk8s kubectl get ing -A
> NAMESPACE     NAME        CLASS    HOSTS   ADDRESS   PORTS   AGE
> kube-system   dashboard   <none>   *                 80      11s
> ```
> 
> Last lines of the ingress container logs:
> 
> ```
> I0225 21:04:04.660923       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583555", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress kube-system/dashboard
> I0225 21:04:04.661260       6 controller.go:141] Configuration changes detected, backend reload required.
> I0225 21:04:04.745626       6 controller.go:157] Backend successfully reloaded.
> I0225 21:04:28.628083       6 status.go:275] updating Ingress kube-system/dashboard status from [] to [{127.0.0.1 }]
> I0225 21:04:28.641134       6 event.go:278] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kube-system", Name:"dashboard", UID:"6a654f27-e98d-4c64-87be-03bbdf621ee5", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"8583595", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kube-system/dashboard
> ```
> 
> Browser gets nothing by Connection Refused errors.
> 
> What am I doing wrong here?

check your TCP port.  You appear to have an ingress listening on port 80 but you have HTTPS setup for your listener.

**Comment by Fischlein18** [comment]
> `kubernetes.io/ingress.class: nginx` change to public. @Rom888

Hi there, 

thanks for posting the ingress configuration file. 
I followed, however on WSL2 (windows 10). It does looks okay:

`$ microk8s kubectl get ingress -n kube-system
NAME        CLASS    HOSTS   ADDRESS     PORTS   AGE
dashboard   <none>   *       127.0.0.1   80      53s`

However, neither "https://127.0.0.1/dashboard" nor "http://127.0.0.1/dashboard" work. ===> 127.0.0.1 refused to connect.

What did I miss? Is this WSL2 thing?

I would really appreciate your help. 

many thanks!!!

**Comment by yanivpaz** [comment]
@jlettman  I see that you already have the fix for this issue . When are you going to submit it to upstream?

**Comment by jlettman** [comment]
> When are you going to submit it to upstream?

@yanivpaz It's submitted for microk8s in PR #2478. I believe that is still under review.

**Comment by yanivpaz** [comment]
@Fischlein18  you can try as WA for WSL2:

```
 microk8s kubectl delete svc kubernetes-dashboard -n kube-system
 microk8s kubectl expose deployment kubernetes-dashboard -n kube-system --type=LoadBalancer --port 8443 --name=kubernetes-dashboard
nodePort=`microk8s kubectl get svc kubernetes-dashboard -n kube-system -o=jsonpath='{.spec.ports[].nodePort}'`
echo https://localhost:$nodePort
```
use the URL above to access the dashboard

**Comment by anthopark** [comment]
> ## option 3
> * Define the ingress as mentioned [here](https://github.com/ubuntu/microk8s/pull/2478/commits/e7eafdb1c13161f49668fdfb198bfebd54834048#diff-140ce8c423142c27928fa6d0cb5324097b04f9af8417d4f1272d10e865be6c79)
> * Run in WSL2 :
> 
> ```
> sudo apt install openssh-server
> sudo systemctl start sshd
> sudo ssh -L 127.0.0.1:443:127.0.0.1:443 username@hostname 
> ```
> 
> add to windows host file
> 
> ```
> 127.0.0.1   kubernetes-dashboard.127.0.0.1.nip.io
> ```
> 
> open https://kubernetes-dashboard.127.0.0.1.nip.io from the browser

@yanivpaz Could you explain what is the reasoning for running `sudo ssh -L 127.0.0.1:443:127.0.0.1:443 username@hostname `?

**Comment by LarsBoosNationalexpress** [comment]
I got it working with microk8s version v1.24.0-2+59bbb3530b6769 and Ubuntu-Server 22.04 LTS.
My ingress-dashboard.yaml looks like this.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: kube-system
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ redirect;
spec:
  # https://kubernetes.io/docs/concepts/services-networking/ingress/
  # https://kubernetes.github.io/ingress-nginx/user-guide/tls/
  rules:
  - http:
      paths:
      - path: /dashboard(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
```

**Comment by one4two** [comment]
Simpler solution

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard.loc
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: dashboard.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
```
