### ISSUE TITLE
Terraform cannot connect to K8s API

### ISSUE THREAD

**Issue by felipecruz91** [ubuntu/microk8s#944]
Hi,

I am trying to deploy some Kubernetes objects to the Microk8s cluster by using Terraform.
The version of Microk8s that I am using is 1.14 from snap.

In my terraform file `main.tf` I have set up the Kubernetes provider:

```tf
provider "kubernetes" {
  load_config_file = true
  config_path = "~/.kube/config"
}
```

When I run `terraform apply`, I get the following error:

```shell
Error: Error applying plan:

2 error(s) occurred:

* kubernetes_service.busybox: 1 error(s) occurred:

* kubernetes_service.busybox: Post http://localhost/api/v1/namespaces/default/services: dial tcp 127.0.0.1:80: connect: connection refused
* kubernetes_deployment.busybox: 1 error(s) occurred:

* kubernetes_deployment.busybox: Failed to create deployment: Post http://localhost/apis/apps/v1/namespaces/default/deployments: dial tcp 127.0.0.1:80: connect: connection refused
```

Apparently Terraform cannot connect to the Kubernetes API that is deployed in Microk8s.

See below my cluster info:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    password: *****
    username: admin
```
